### ISSUE TITLE
Versions, OS and fluff

### ISSUE THREAD

**Issue by userbradley** [mikecao/umami#1]
Hey Man,

Project looks pretty awesome! Just having issues installing it.

Are you able to let me know the following:

* Supported OS'
* NPM version
* mysql version (not _too_ important) 

as I am having some whack issues installing (log file attached hopefully) and I think, tho I am not sure, it seems to be an NPM issue or an OS related issue.

(Also, the demo site gets a 502)
[2020-08-18T12_02_17_269Z-debug.log](https://github.com/mikecao/umami/files/5090239/2020-08-18T12_02_17_269Z-debug.log)

I am running on a clean install of ubuntu 18.04 

```
ubuntu@umami:~$ npm -v
6.14.8
ubuntu@umami:~$ node -v
v8.10.0
ubuntu@umami:~$ hostnamectl
   Static hostname: umami
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ab8c10e8c0f642ea8d8458e417d700f2
           Boot ID: 59aa74b39f004832ad40340a1b2c34bb
    Virtualization: xen
  Operating System: Ubuntu 18.04.5 LTS
            Kernel: Linux 4.15.0-112-generic
      Architecture: x86-64
ubuntu@umami:~$
```

**Comment by mikecao** [comment]
Any OS that runs node is supported. The app however runs Next.js which requires Node 10.13 or later.

**Comment by userbradley** [comment]
Yeah still having issues. I though it could be an issue with the ubuntu image so I did a fresh install and tried ubuntu 20.04 and had similar issues

```
root@umami:~/umami# npm install
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> @prisma/cli@2.5.1 preinstall /root/umami/node_modules/@prisma/cli
> node preinstall/index.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/umami/node_modules/@prisma/cli/preinstall/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @prisma/cli@2.5.1 preinstall: `node preinstall/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @prisma/cli@2.5.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-25T19_39_17_638Z-debug.log
root@umami:~/umami# 
```
---
```
root@umami:~/umami# node -v
v10.19.0
```
---
```
root@umami:~/umami# hostnamectl
   Static hostname: umami
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 1351aca7593b4a799eb0dfbbed10ec52
           Boot ID: b680f511c1124327a3f4291fdf190165
    Virtualization: xen
  Operating System: Ubuntu 20.04 LTS
            Kernel: Linux 5.4.0-26-generic
      Architecture: x86-64
root@umami:~/umami# 
```
Any clues?

**Comment by mikecao** [comment]
That's an odd error. Since it's happening with NPM there's not much I can do. All I can say is try installing with the latest version of node.

**Comment by userbradley** [comment]
I've been doing that 😛 

When you installed it, what were the commands you were running? (eg, walk through of installing from a fresh install of linux)

I think maybe i'm doing something whack.

Thanks

-Brad

**Comment by mikecao** [comment]
I just tried on a new ubuntu and it ran fine, although I am using node 14.8. You can also try using yarn instead, which is more reliable.
