### ISSUE TITLE
Unable to upgrade to 1.27.0 : husky not found 

### ISSUE THREAD

**Issue by meepmeep** [mikecao/umami#1005]
I tried to upgrade this morning to 1.27.0 with the usual **git pull ; npm install ; npm run build**

But I got this (new) error about husky :

```
> umami@1.27.0 prepare
> husky install

sh: 1: husky: not found
npm ERR! code 127
npm ERR! path /home/lufi/umami
npm ERR! command failed
npm ERR! command sh -c husky install

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lufi/.npm/_logs/2022-03-03T09_12_18_648Z-debug-0.log

> umami@1.27.0 build
> npm-run-all build-tracker build-geo build-db build-app


> umami@1.27.0 build-tracker
> rollup -c rollup.tracker.config.js

[!] Error: Cannot find module '@rollup/plugin-buble'
Require stack:
- /home/lufi/umami/rollup.tracker.config.js
- /usr/lib/node_modules/rollup/dist/shared/loadConfigFile.js
- /usr/lib/node_modules/rollup/dist/bin/rollup
Error: Cannot find module '@rollup/plugin-buble'
Require stack:
- /home/lufi/umami/rollup.tracker.config.js
- /usr/lib/node_modules/rollup/dist/shared/loadConfigFile.js
- /usr/lib/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/lufi/umami/rollup.tracker.config.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.require.extensions.<computed> [as .js] (/usr/lib/node_modules/rollup/dist/shared/loadConfigFile.js:560:20)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)

ERROR: "build-tracker" exited with 1.

```

I tried : npm install husky husky-init
Same error.

How could I resolve that ?

**Comment by meepmeep** [comment]
'yarn husky install" fixed that one.
