### ISSUE TITLE
[Bug] 500 (Internal Server Error) while trying to edit website

### ISSUE THREAD

**Issue by dakshshah96** [mikecao/umami#101]
While trying to edit a website and trying to save it, the request fails with `500 (Internal Server Error)`. These are the logs:

**Output logs:**

```
exising id null {
    website_id: 1,
    website_uuid: 'uuid-goes-here',
    name: 'Name goes here',
    created_at: 2020-09-04T13:29:40.049Z,
    user_id: 3,
    domain: 'umami.domain.com',
    share_id: null
}
```

**Error logs:**

```
PrismaClientKnownRequestError: Missing a required value at `Mutation.updateOnewebsite.data.websiteUpdateInput.share_id`
    at PrismaClientFetcher.request (/home/ubuntu/umami/node_modules/@prisma/client/runtime/index.js:1:228179)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    code: 'P2012',
    meta: {
        path: 'Mutation.updateOnewebsite.data.websiteUpdateInput.share_id'
    }
}
```

**Comment by mikecao** [comment]
Was a problem with the latest prisma update. I just pushed out a fix. Pull the latest and reinstall your dependencies.

**Comment by mikecao** [comment]
Is this still an issue?
