### ISSUE TITLE
⚡ Umami postgresql-v1.29.0 docker container fails on startup

### ISSUE THREAD

**Issue by OCram85** [mikecao/umami#1067]
Just updated my umami instances from `1.28.0` to `1.29.0`.

🔥  The container stops with:

```
yarn run v1.22.17
$ npm-run-all init start-app
/bin/sh: npm-run-all: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Tested with tags `postgresql-latest` and `postgresql-v1.29.0`

**Comment by mikecao** [comment]
Can you try pulling the latest `v1.29.1`?

**Comment by OCram85** [comment]
Just tested with `v1.29.1`  🔥 :

```
yarn run v1.22.17
$ npm-run-all init start-app
$ node scripts/prestart.js
internal/modules/cjs/loader.js:818

  throw err;
  ^
Error: Cannot find module '/app/scripts/prestart.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "init" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mikecao** [comment]
Please try again with `v1.29.2`

**Comment by OCram85** [comment]
Awesome !! 🔥 🧯 🚒  👍 

Container successfully started 👍  thank you!
