### ISSUE TITLE
Auto migrate & seed database on docker container start

### ISSUE THREAD

**Issue by anbraten** [mikecao/umami#1154]
With #580 (#559) prisma migration files have been added. It would be super nice if those migrations could be auto-applied on container start (maybe with the option to disable it). This would help a lot with deploying umami to systems like Kubernetes or larger database cluster were it is pretty hard to get the migration files into the database.

My idea would be to add the migration files to the docker image(s) and execute `yarn prisma migrate deploy` before doing `yarn start`. If this is wanted I would be happy to open a PR. 🙏🏾

**Comment by DrMxrcy** [comment]
This would be great

**Comment by mikecao** [comment]
We are going to start doing real migrations pretty soon so this will probably be needed.

**Comment by waptik** [comment]
This would be great because when i try to deploy the app on qovery, I get the errors found below. Meaning the schema and migrations have not uploaded to the database.

```sh

PrismaClientKnownRequestError: The table `public.account` does not exist in the current database.
--
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at Object.request (/app/node_modules/@prisma/client/runtime/index.js:45405:15)
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:46301:18)
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/auth/login.js:85:21)
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:182:9)
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:386:9)
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at async Object.fn (/app/node_modules/next/dist/server/base-server.js:488:37)
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at async Router.execute (/app/node_modules/next/dist/server/router.js:228:32)
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:600:29)
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:307:20)
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | at async Server.<anonymous> (/app/server.js:16:5) {
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | code: 'P2021',
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | clientVersion: '3.14.0',
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | meta: { table: 'public.account' }
14 Jun, 10:03:20.194 | app-zff2f7a9e-0 |   | }

```

**Comment by anbraten** [comment]
The PR got merged, so it should be available in the next version. Closing.

**Comment by waptik** [comment]
> The PR got merged, so it should be available in the next version. Closing.

Thanks!
