### ISSUE TITLE
Error - Generating pages (Creating an optimized production build)

### ISSUE THREAD

**Issue by foxytocin** [mikecao/umami#1226]
Can't build the current version of umami. Tried npm as well as yarn. It always ends up like this:

info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data

[    ] info  - Generating static pages (0/13)
Error occurred prerendering page "/dashboard/[[...id]]". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (/Users/xxx/LokaleDaten/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:11:316)
    at B (/Users/xxx/LokaleDaten/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:12:166)
    at W (/Users/xxx/LokaleDaten/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:20:375)
    at Object.useMemo (/Users/xxx/LokaleDaten/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:23:164)
    at useTransition (/Users/andreas/LokaleDaten/umami/node_modules/react-spring/node_modules/@react-spring/core/dist/react-spring-core.cjs.prod.js:2156:21)
    at ThemeButton (/Users/xxx/LokaleDaten/umami/.next/server/chunks/7124.js:1150:82)
    at d (/Users/xxx/LokaleDaten/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/Users/xxx/LokaleDaten/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/Users/xxx/LokaleDaten/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/Users/xxx/LokaleDaten/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)

Error occurred prerendering page "/settings/profile". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error occurred prerendering page "/test". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

Error occurred prerendering page "/settings". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

Error occurred prerendering page "/settings/accounts". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

Error occurred prerendering page "/realtime". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

> Build error occurred
Error: Export encountered errors on following paths:
        /404
        /dashboard/[[...id]]
        /realtime
        /settings
        /settings/accounts
        /settings/profile
        /test
    at /Users/xxx/LokaleDaten/umami/node_modules/next/dist/export/index.js:498:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/Users/xxx/LokaleDaten/umami/node_modules/next/dist/trace/trace.js:75:20)
    at async /Users/xxx/LokaleDaten/umami/node_modules/next/dist/build/index.js:1024:17
    at async Span.traceAsyncFn (/Users/xxx/LokaleDaten/umami/node_modules/next/dist/trace/trace.js:75:20)
    at async /Users/xxx/LokaleDaten/umami/node_modules/next/dist/build/index.js:898:13
    at async Span.traceAsyncFn (/Users/xxx/LokaleDaten/umami/node_modules/next/dist/trace/trace.js:75:20)
    at async Object.build [as default] (/Users/xxx/LokaleDaten/umami/node_modules/next/dist/build/index.js:82:25)
ERROR: "build-app" exited with 1.

**Comment by foxytocin** [comment]
Maybe this is a local problem of my environment.

**Comment by mikecao** [comment]
Seems like it. What is your envrionment?
