### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by grischoun** [mikecao/umami#136]
When I try to login the very first time right after installation I get the below error. Any hint on what is going on?

```
ready - started server on http://localhost:3000
PrismaClientInitializationError: Error parsing connection string: invalid port number
    at PrismaClientFetcher.request (/home/softpeel/umami/node_modules/@prisma/client/runtime/index.js:1:228562)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports.Nrn6.__webpack_exports__.default (/home/softpeel/umami/.next/server/pages/api/auth/login.js:139:19)
    at async apiResolver (/home/softpeel/umami/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async Server.handleApiRequest (/home/softpeel/umami/node_modules/next/dist/next-server/server/next-server.js:47:397)
    at async Object.fn (/home/softpeel/umami/node_modules/next/dist/next-server/server/next-server.js:39:218)
    at async Router.execute (/home/softpeel/umami/node_modules/next/dist/next-server/server/router.js:23:67)
    at async Server.run (/home/softpeel/umami/node_modules/next/dist/next-server/server/next-server.js:49:494)
    at async Server.handleRequest (/home/softpeel/umami/node_modules/next/dist/next-server/server/next-server.js:17:101)
```

**Comment by mikecao** [comment]
You can a problem with your database connection string, `Error parsing connection string: invalid port number`

**Comment by grischoun** [comment]
Ah yes, there was a special character in the URL and it could not be parsed correctly. It works now. Thanks!
