### ISSUE TITLE
dashboard error after adding new website

### ISSUE THREAD

**Issue by haq** [mikecao/umami#22]
Hi, I am getting this error when I visit the dashboard after I have added a website. If I delete the website everything goes back to normal.

I am running this in a docker container so could this be a problem with the image? 

### docker file
```Dockerfile
FROM node:latest

COPY . /app
WORKDIR /app

RUN npm install \
 && npm run build-mysql-client \
 && npm run build

EXPOSE 3000
CMD ["npm", "start"]
```

### error
```text
PrismaClientKnownRequestError: Raw query failed. Code: `1305`. Message: `FUNCTION umami.date_trunc does not exist`
    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:1:211077)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async module.exports.cmhW.__webpack_exports__.default (/app/.next/server/pages/api/website/[id]/pageviews.js:542:32)
    at async apiResolver (/app/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async Server.handleApiRequest (/app/node_modules/next/dist/next-server/server/next-server.js:48:397)
    at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:40:218)
    at async Router.execute (/app/node_modules/next/dist/next-server/server/router.js:38:67)
    at async Server.run (/app/node_modules/next/dist/next-server/server/next-server.js:49:494)
    at async Server.handleRequest (/app/node_modules/next/dist/next-server/server/next-server.js:18:101) {
  code: 'P2010',
  meta: { code: '1305', message: 'FUNCTION umami.date_trunc does not exist' }
}
```

### docker build log
<details>

<p>

```text
[root@tyr umami]# docker build -t umami .
Sending build context to Docker daemon  1.508MB
Step 1/6 : FROM node:latest
latest: Pulling from library/node
419e7ae5bb1e: Pull complete 
848839e0cd3b: Pull complete 
de30e8b35015: Pull complete 
258fdea6ea48: Pull complete 
ddb75eb7f1e9: Pull complete 
7ec8a0667334: Pull complete 
c6d8dab5779d: Pull complete 
d3ae9be01b42: Pull complete 
38ff96b6f833: Pull complete 
Digest: sha256:8b6401f8d15c900736a54a870994277b3de19ebd28cc483c497bf00d608e2a90
Status: Downloaded newer image for node:latest
 ---> 784e696f5060
Step 2/6 : COPY . /app
 ---> 6a7293be4d29
Step 3/6 : WORKDIR /app
 ---> Running in 45926c6c0e66
Removing intermediate container 45926c6c0e66
 ---> 1f4edb969ff2
Step 4/6 : RUN npm install  && npm run build-mysql-client  && npm run build
 ---> Running in 4d722d03fcf0
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> @prisma/cli@2.4.1 preinstall /app/node_modules/@prisma/cli
> node preinstall/index.js


> @prisma/cli@2.4.1 install /app/node_modules/@prisma/cli
> node download-build/index.js


> bcrypt@5.0.0 install /app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[bcrypt] Success: "/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote

> husky@4.2.5 install /app/node_modules/husky
> node husky install

husky > Setting up git hooks
Husky requires Git >=2.13.0. Got v2.11.0.
husky > Failed to install

> @ampproject/toolbox-optimizer@2.6.0 postinstall /app/node_modules/@ampproject/toolbox-optimizer
> node lib/warmup.js

AMP OPTIMIZER Downloaded latest AMP runtime data.

> @prisma/client@2.4.1 postinstall /app/node_modules/@prisma/client
> node scripts/postinstall.js

warning The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you have a Prisma Schema file in a custom path, you will need to run
`prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
If you do not have a Prisma Schema file yet, you can ignore this message.


> geolite2-redist@1.0.7 postinstall /app/node_modules/geolite2-redist
> node scripts/postinstall.js

Downloading MaxMind databases from mirror...

> husky@4.2.5 postinstall /app/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.8.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1389 packages from 653 contributors and audited 1394 packages in 28.682s

132 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> umami@0.9.0 build-mysql-client /app
> dotenv prisma generate -- --schema=./prisma/schema.mysql.prisma


✔ Generated Prisma Client to ./node_modules/@prisma/client in 52ms

You can now start using Prisma Client in your code:

import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

Explore the full API: http://pris.ly/d/client

> umami@0.9.0 build /app
> next build

info  - Loaded env from /app/.env
info  - Creating an optimized production build...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/10)
info  - Generating static pages (1/10)
info  - Generating static pages (2/10)
info  - Generating static pages (3/10)
info  - Generating static pages (4/10)
info  - Generating static pages (5/10)
info  - Generating static pages (6/10)
info  - Generating static pages (7/10)
info  - Generating static pages (8/10)
info  - Generating static pages (9/10)
info  - Generating static pages (10/10)
info  - Finalizing page optimization...

Page                                                           Size     First Load JS
┌ ○ /                                                          270 B          69.7 kB
├   /_app                                                      0 B            69.4 kB
├ ○ /404                                                       311 B          83.3 kB
├ ○ /account                                                   300 B           108 kB
├   └ css/d6ce35f156ff7a395d80.css                             1.59 kB
├ λ /api/account                                               0 B            69.4 kB
├ λ /api/account/[id]                                          0 B            69.4 kB
├ λ /api/account/password                                      0 B            69.4 kB
├ λ /api/accounts                                              0 B            69.4 kB
├ λ /api/auth/login                                            0 B            69.4 kB
├ λ /api/auth/logout                                           0 B            69.4 kB
├ λ /api/auth/verify                                           0 B            69.4 kB
├ λ /api/collect                                               0 B            69.4 kB
├ λ /api/share/[id]                                            0 B            69.4 kB
├ λ /api/website                                               0 B            69.4 kB
├ λ /api/website/[id]                                          0 B            69.4 kB
├ λ /api/website/[id]/active                                   0 B            69.4 kB
├ λ /api/website/[id]/metrics                                  0 B            69.4 kB
├ λ /api/website/[id]/pageviews                                0 B            69.4 kB
├ λ /api/website/[id]/rankings                                 0 B            69.4 kB
├ λ /api/websites                                              0 B            69.4 kB
├ ○ /dashboard                                                 1.3 kB          269 kB
├   └ css/3863ae50099d5da20e76.css                             1.8 kB
├ ○ /login                                                     963 B           105 kB
├   └ css/83201af397b3b9674650.css                             1.33 kB
├ ○ /logout                                                    317 B          69.8 kB
├ ○ /settings                                                  4.84 kB         113 kB
├   └ css/2bde8e151308fa3094e9.css                             1.91 kB
├ ○ /share/[...id]                                             692 B           318 kB
├ ○ /test                                                      689 B          83.6 kB
└ ○ /website/[...id]                                           811 B           318 kB
+ First Load JS shared by all                                  69.4 kB
  ├ chunks/0328004b18dbca9d70f9be5bfa3108943c47d56c.1cd369.js  5.98 kB
  ├ chunks/500b5a1d2b643a4c391e5b5b5d3aac2b96523de3.078c38.js  4.82 kB
  ├ chunks/ed2584126e27a96ef798621a2b6886b4a721d4b7.e68a13.js  10 kB
  ├ chunks/framework.4cba9b.js                                 40.4 kB
  ├ chunks/main.0bf0ed.js                                      6.69 kB
  ├ chunks/pages/_app.312cc1.js                                747 B
  ├ chunks/webpack.ccf5ab.js                                   751 B
  └ css/919eb8d609481187f7f6.css                               6.54 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

Redirects

┌ source: /:path+/
├ destination: /:path+
└ permanent: true
 

Removing intermediate container 4d722d03fcf0
 ---> b993867a7910
Step 5/6 : EXPOSE 3000
 ---> Running in 2ad3eb6a290f
Removing intermediate container 2ad3eb6a290f
 ---> 73c32347972b
Step 6/6 : CMD ["npm", "start"]
 ---> Running in e99c976431ba
Removing intermediate container e99c976431ba
 ---> d1221032d1f1
Successfully built d1221032d1f1
Successfully tagged umami:latest
```

</p>
</details>

**Comment by mikecao** [comment]
This should have been fixed in the latest version. There was an error in the mysql import script. You can just connect to your database and run the create function code from the `schema.mysql.sql` file to fix it.

**Comment by haq** [comment]
> This should have been fixed in the latest version. There was an error in the mysql import script. You can just connect to your database and run the create function code from the `schema.mysql.sql` file to fix it.

Issue fixed. :)
