### ISSUE TITLE
[Error]: Unique constraint failed on the fields: (`session_uuid`)

### ISSUE THREAD

**Issue by dakshshah96** [mikecao/umami#232]
For the last few days, my self-hosted version of Umami keeps crashing. When I check the application logs, I see an endless stream of these errors and then the server gets overloaded and shuts down.

The `Unique constraint failed on the fields` part is the one that's repeated well over a thousand times in the logs.

```
2020-09-27T16:09:48.722408876Z app[web.1]: Ap [Error]: Unique constraint failed on the fields: (`session_uuid`)
2020-09-27T16:09:48.722437377Z app[web.1]:     at iy.request (/app/node_modules/@prisma/client/runtime/index.js:196:54)
2020-09-27T16:09:48.722442587Z app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-09-27T16:09:48.722447212Z app[web.1]:   code: 'P2002',
2020-09-27T16:09:48.722451522Z app[web.1]:   meta: { target: [ 'session_uuid' ] }
2020-09-27T16:09:48.722455517Z app[web.1]: }
2020-09-27T16:15:52.782199022Z app[web.1]: Ap [Error]: Unique constraint failed on the fields: (`session_uuid`)
2020-09-27T16:15:52.782231631Z app[web.1]:     at iy.request (/app/node_modules/@prisma/client/runtime/index.js:196:54)
2020-09-27T16:15:52.782236995Z app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-09-27T16:15:52.782241698Z app[web.1]:   code: 'P2002',
2020-09-27T16:15:52.782245688Z app[web.1]:   meta: { target: [ 'session_uuid' ] }
2020-09-27T16:15:52.782249653Z app[web.1]: }
2020-09-27T16:27:53.661297831Z app[web.1]: Ap [Error]: Unique constraint failed on the fields: (`session_uuid`)
2020-09-27T16:27:53.661331610Z app[web.1]:     at iy.request (/app/node_modules/@prisma/client/runtime/index.js:196:54)
2020-09-27T16:27:53.661337294Z app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-09-27T16:27:53.661341907Z app[web.1]:   code: 'P2002',
2020-09-27T16:27:53.661355859Z app[web.1]:   meta: { target: [ 'session_uuid' ] }
2020-09-27T16:27:53.661359670Z app[web.1]: }
2020-09-27T16:29:44.665302396Z app[web.1]: Ap [Error]: Unique constraint failed on the fields: (`session_uuid`)
2020-09-27T16:29:44.665335030Z app[web.1]:     at iy.request (/app/node_modules/@prisma/client/runtime/index.js:196:54)
2020-09-27T16:29:44.665340744Z app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-09-27T16:29:44.665345312Z app[web.1]:   code: 'P2002',
2020-09-27T16:29:44.665349624Z app[web.1]:   meta: { target: [ 'session_uuid' ] }
2020-09-27T16:29:44.665353574Z app[web.1]: }
2020-09-29T08:48:20.047069134Z app[web.1]: /app/node_modules/geolite2-redist/scripts/download-helper.js:36
2020-09-29T08:48:20.047103431Z app[web.1]: 						throw new Error(`Could not fetch checksum for ${edition.name}\n\nReceived:\n${checksum}`);
2020-09-29T08:48:20.047112278Z app[web.1]: 						^
2020-09-29T08:48:20.047116847Z app[web.1]:
2020-09-29T08:48:20.047120732Z app[web.1]: Error: Could not fetch checksum for GeoLite2-Country
2020-09-29T08:48:20.047124721Z app[web.1]:
2020-09-29T08:48:20.047128523Z app[web.1]: Received:
2020-09-29T08:48:20.047132309Z app[web.1]: <?xml version="1.0" encoding="utf-8"?>
2020-09-29T08:48:20.047136673Z app[web.1]: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
2020-09-29T08:48:20.047140749Z app[web.1]:  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
2020-09-29T08:48:20.047144663Z app[web.1]: <html>
2020-09-29T08:48:20.047148526Z app[web.1]:   <head>
2020-09-29T08:48:20.047152350Z app[web.1]:     <title>503 Backend unavailable, connection timeout</title>
2020-09-29T08:48:20.047157195Z app[web.1]:   </head>
2020-09-29T08:48:20.047170626Z app[web.1]:   <body>
2020-09-29T08:48:20.047174321Z app[web.1]:     <h1>Error 503 Backend unavailable, connection timeout</h1>
2020-09-29T08:48:20.047178072Z app[web.1]:     <p>Backend unavailable, connection timeout</p>
2020-09-29T08:48:20.047181763Z app[web.1]:     <h3>Guru Mediation:</h3>
2020-09-29T08:48:20.047185210Z app[web.1]:     <p>Details: cache-del21738-DEL 1601369300 2439466243</p>
2020-09-29T08:48:20.047188835Z app[web.1]:     <hr>
2020-09-29T08:48:20.047192079Z app[web.1]:     <p>Varnish cache server</p>
2020-09-29T08:48:20.047195648Z app[web.1]:   </body>
2020-09-29T08:48:20.047198947Z app[web.1]: </html>
2020-09-29T08:48:20.047202387Z app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/geolite2-redist/scripts/download-helper.js:36:13)
2020-09-29T08:48:20.047206187Z app[web.1]:     at IncomingMessage.emit (events.js:327:22)
2020-09-29T08:48:20.047209647Z app[web.1]:     at endReadableNT (_stream_readable.js:1220:12)
2020-09-29T08:48:20.047213117Z app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-09-29T08:48:20.059069441Z app[web.1]: npm ERR! code ELIFECYCLE
2020-09-29T08:48:20.059534046Z app[web.1]: npm ERR! errno 1
2020-09-29T08:48:20.061504045Z app[web.1]: npm ERR! umami@0.48.0 start: `next start`
2020-09-29T08:48:20.061770538Z app[web.1]: npm ERR! Exit status 1
2020-09-29T08:48:20.062033155Z app[web.1]: npm ERR!
2020-09-29T08:48:20.062275673Z app[web.1]: npm ERR! Failed at the umami@0.48.0 start script.
2020-09-29T08:48:20.062513391Z app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-29T08:48:20.073971098Z app[web.1]:
2020-09-29T08:48:20.074331495Z app[web.1]: npm ERR! A complete log of this run can be found in:
2020-09-29T08:48:20.074555871Z app[web.1]: npm ERR!     /app/.npm/_logs/2020-09-29T08_48_20_067Z-debug.log
```

**Comment by mikecao** [comment]
You need to upgrade to the latest version in master.

**Comment by dakshshah96** [comment]
> You need to upgrade to the latest version in master.

I see that I'm one version behind right now. Was this a bug that got fixed? Just curious.

**Comment by mikecao** [comment]
Yes, there are always bug fixes going straight to `master`. I generally develop new features in the `dev` branch, but `master` will always have that latest usable version. The version under releases is not always the latest.

**Comment by dakshshah96** [comment]
> Yes, there are always bug fixes going straight to `master`. I generally develop new features in the `dev` branch, but `master` will always have that latest usable version. The version under releases is not always the latest.

Understood! I'll make sure to keep track of `master` now instead of Releases. Thanks for the clarification!

**Comment by loguu** [comment]
Hi @mikecao , I'm still having this issue with 1.7.0. It will always crash when there are a lot of visits.

```
{"log":"PrismaClientKnownRequestError2: Unique constraint failed on the fields: (`session_uuid`)\n","stream":"stderr","time":"2020-11-30T05:54:01.147810834Z"}
{"log":"    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:79355:15)\n","stream":"stderr","time":"2020-11-30T05:54:01.147836302Z"}
{"log":"    at runMicrotasks (\u003canonymous\u003e)\n","stream":"stderr","time":"2020-11-30T05:54:01.147841399Z"}
{"log":"    at processTicksAndRejections (internal/process/task_queues.js:97:5) {\n","stream":"stderr","time":"2020-11-30T05:54:01.147846595Z"}
{"log":"  code: 'P2002',\n","stream":"stderr","time":"2020-11-30T05:54:01.147850677Z"}
{"log":"  clientVersion: '2.12.1',\n","stream":"stderr","time":"2020-11-30T05:54:01.147854454Z"}
{"log":"  meta: { target: [ 'session_uuid' ] }\n","stream":"stderr","time":"2020-11-30T05:54:01.147858389Z"}
{"log":"}\n","stream":"stderr","time":"2020-11-30T05:54:01.14786212Z"}
{"log":"PrismaClientKnownRequestError2: Unique constraint failed on the fields: (`session_uuid`)\n","stream":"stderr","time":"2020-11-30T06:12:39.971949193Z"}
{"log":"    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:79355:15)\n","stream":"stderr","time":"2020-11-30T06:12:39.971976282Z"}
{"log":"    at runMicrotasks (\u003canonymous\u003e)\n","stream":"stderr","time":"2020-11-30T06:12:39.971981362Z"}
{"log":"    at processTicksAndRejections (internal/process/task_queues.js:97:5) {\n","stream":"stderr","time":"2020-11-30T06:12:39.971986113Z"}
{"log":"  code: 'P2002',\n","stream":"stderr","time":"2020-11-30T06:12:39.971990091Z"}
{"log":"  clientVersion: '2.12.1',\n","stream":"stderr","time":"2020-11-30T06:12:39.971993859Z"}
{"log":"  meta: { target: [ 'session_uuid' ] }\n","stream":"stderr","time":"2020-11-30T06:12:39.971997794Z"}
{"log":"}\n","stream":"stderr","time":"2020-11-30T06:12:39.972016383Z"}
{"log":"PrismaClientKnownRequestError2: The provided value for the column is too long for the column's type. Column: \u003cunknown\u003e\n","stream":"stderr","time":"2020-11-30T06:51:35.667570222Z"}
{"log":"    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:79355:15)\n","stream":"stderr","time":"2020-11-30T06:51:35.668759345Z"}
{"log":"    at runMicrotasks (\u003canonymous\u003e)\n","stream":"stderr","time":"2020-11-30T06:51:35.668765087Z"}
{"log":"    at processTicksAndRejections (internal/process/task_queues.js:97:5) {\n","stream":"stderr","time":"2020-11-30T06:51:35.668769494Z"}
{"log":"  code: 'P2000',\n","stream":"stderr","time":"2020-11-30T06:51:35.668773529Z"}
{"log":"  clientVersion: '2.12.1',\n","stream":"stderr","time":"2020-11-30T06:51:35.668780775Z"}
{"log":"  meta: { column_name: '\u003cunknown\u003e' }\n","stream":"stderr","time":"2020-11-30T06:51:35.668784555Z"}
{"log":"}\n","stream":"stderr","time":"2020-11-30T06:51:35.668788609Z"}
{"log":"PrismaClientKnownRequestError2: Unique constraint failed on the fields: (`session_uuid`)\n","stream":"stderr","time":"2020-11-30T07:03:29.465787166Z"}
{"log":"    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:79355:15)\n","stream":"stderr","time":"2020-11-30T07:03:29.465813436Z"}
{"log":"    at runMicrotasks (\u003canonymous\u003e)\n","stream":"stderr","time":"2020-11-30T07:03:29.465818459Z"}
{"log":"    at processTicksAndRejections (internal/process/task_queues.js:97:5) {\n","stream":"stderr","time":"2020-11-30T07:03:29.465823834Z"}
{"log":"  code: 'P2002',\n","stream":"stderr","time":"2020-11-30T07:03:29.465827868Z"}
{"log":"  clientVersion: '2.12.1',\n","stream":"stderr","time":"2020-11-30T07:03:29.465831656Z"}
{"log":"  meta: { target: [ 'session_uuid' ] }\n","stream":"stderr","time":"2020-11-30T07:03:29.465835501Z"}
{"log":"}\n","stream":"stderr","time":"2020-11-30T07:03:29.465839316Z"}
```

There are two kinds of errors here:
1. `PrismaClientKnownRequestError2: Unique constraint failed on the fields: (`session_uuid`)`
2. `PrismaClientKnownRequestError2: The provided value for the column is too long for the column's type. Column: \u003cunknown\u003e`
