### ISSUE TITLE
Error: Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by KonstantinReido** [mikecao/umami#248]
Trying to deploy Umami 0.67.0 on Heroku

```
2020-10-01T14:33:14.879818+00:00 heroku[web.1]: Starting process with command `npm start`
2020-10-01T14:33:17.212827+00:00 app[web.1]:
2020-10-01T14:33:17.212841+00:00 app[web.1]: > umami@0.67.0 start /app
2020-10-01T14:33:17.212842+00:00 app[web.1]: > next start
2020-10-01T14:33:17.212842+00:00 app[web.1]:
2020-10-01T14:33:17.438968+00:00 app[web.1]: Error: Cannot find module 'dotenv'
2020-10-01T14:33:17.438970+00:00 app[web.1]: Require stack:
2020-10-01T14:33:17.438970+00:00 app[web.1]: - /app/next.config.js
2020-10-01T14:33:17.438970+00:00 app[web.1]: - /app/node_modules/next/dist/next-server/server/config.js
2020-10-01T14:33:17.438970+00:00 app[web.1]: - /app/node_modules/next/dist/next-server/server/next-server.js
2020-10-01T14:33:17.438971+00:00 app[web.1]: - /app/node_modules/next/dist/server/next.js
2020-10-01T14:33:17.438971+00:00 app[web.1]: - /app/node_modules/next/dist/server/lib/start-server.js
2020-10-01T14:33:17.438971+00:00 app[web.1]: - /app/node_modules/next/dist/cli/next-start.js
2020-10-01T14:33:17.438972+00:00 app[web.1]: - /app/node_modules/next/dist/bin/next
2020-10-01T14:33:17.438972+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
2020-10-01T14:33:17.438972+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:841:27)
2020-10-01T14:33:17.438973+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:1025:19)
2020-10-01T14:33:17.438973+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:72:18)
2020-10-01T14:33:17.438973+00:00 app[web.1]: at Object.<anonymous> (/app/next.config.js:1:1)
2020-10-01T14:33:17.438973+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1137:30)
2020-10-01T14:33:17.438973+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2020-10-01T14:33:17.438974+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:985:32)
2020-10-01T14:33:17.438974+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2020-10-01T14:33:17.438974+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:1025:19) {
2020-10-01T14:33:17.438974+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2020-10-01T14:33:17.438975+00:00 app[web.1]: requireStack: [
2020-10-01T14:33:17.438975+00:00 app[web.1]: '/app/next.config.js',
2020-10-01T14:33:17.438975+00:00 app[web.1]: '/app/node_modules/next/dist/next-server/server/config.js',
2020-10-01T14:33:17.438975+00:00 app[web.1]: '/app/node_modules/next/dist/next-server/server/next-server.js',
2020-10-01T14:33:17.438975+00:00 app[web.1]: '/app/node_modules/next/dist/server/next.js',
2020-10-01T14:33:17.438976+00:00 app[web.1]: '/app/node_modules/next/dist/server/lib/start-server.js',
2020-10-01T14:33:17.438976+00:00 app[web.1]: '/app/node_modules/next/dist/cli/next-start.js',
2020-10-01T14:33:17.438976+00:00 app[web.1]: '/app/node_modules/next/dist/bin/next'
2020-10-01T14:33:17.438976+00:00 app[web.1]: ]
2020-10-01T14:33:17.438976+00:00 app[web.1]: }
2020-10-01T14:33:17.447476+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-10-01T14:33:17.447762+00:00 app[web.1]: npm ERR! errno 1
2020-10-01T14:33:17.451046+00:00 app[web.1]: npm ERR! umami@0.67.0 start: `next start`
2020-10-01T14:33:17.451179+00:00 app[web.1]: npm ERR! Exit status 1
2020-10-01T14:33:17.451335+00:00 app[web.1]: npm ERR!
2020-10-01T14:33:17.451468+00:00 app[web.1]: npm ERR! Failed at the umami@0.67.0 start script.
2020-10-01T14:33:17.451598+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-10-01T14:33:17.461266+00:00 app[web.1]:
2020-10-01T14:33:17.461505+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-10-01T14:33:17.461606+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-10-01T14_33_17_454Z-debug.log
2020-10-01T14:33:17.532369+00:00 heroku[web.1]: Process exited with status 1
2020-10-01T14:33:17.565301+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by KonstantinReido** [comment]
I moved `dotenv` package from devDependencies to dependencies section in package.json and it solved the issue for me. But you need to look at it.

**Comment by mikecao** [comment]
I probably shouldn't have included `dotenv` in the script since it's a production start anyways. Will fix, thanks.

**Comment by mikecao** [comment]
Removed `dotenv` from the script in the latest release.
