### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by dannluciano** [mikecao/umami#34]
Message from Front End: ```An unexpected error has occurred.```

When a run `SELECT * FROM events;` in Postgresql this return an empty table.

Log from Front End:
```
17:51:22.925
TypeError: u is null
    NextJS 20
framework.4cba9b13ac7d2f11afcf.js:1:99659
    NextJS 22
17:51:22.926
TypeError: u is null
    NextJS 20
        we
        Gi
        Ua
        ko
        xu
        wu
        du
        Xl
        unstable_runWithPriority
        $l
        Xl
        Yl
        ou
        ga
        e
        h
        _invoke
        S
        r
        s
```

Log from Server:
```
info  - Loaded env from /var/www/umami/.env
ready - started server on http://localhost:3000
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports.RKDr.__webpack_exports__.default (/var/www/umami/.next/server/pages/api/website/[id]/metrics.js:523:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async apiResolver (/var/www/umami/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async Server.handleApiRequest (/var/www/umami/node_modules/next/dist/next-server/server/next-server.js:48:397)
    at async Object.fn (/var/www/umami/node_modules/next/dist/next-server/server/next-server.js:40:218)
    at async Router.execute (/var/www/umami/node_modules/next/dist/next-server/server/router.js:38:67)
    at async Server.run (/var/www/umami/node_modules/next/dist/next-server/server/next-server.js:49:494)
    at async Server.handleRequest (/var/www/umami/node_modules/next/dist/next-server/server/next-server.js:18:101)
```

**Comment by mikecao** [comment]
Events aren't implemented yet. Yes there is an events table and code to collect events but no UI. It's coming.

**Comment by mikecao** [comment]
Events are now available.
