### ISSUE TITLE
CDN Issue

### ISSUE THREAD

**Issue by SuLingGG** [mikecao/umami#350]
I deployed umami by docker, first I use not modified Dockerfile to build docker image on Dockerhub, then pull & run Docker container use `docker-compose` to start up containers in my VPS.

When I visit http://ip:3000, no error occurred.

But when I try to use CDN to reverse proxy http://ip:3000 by https and visit https://cdn-domain:443, I get error on Dashboard page:

![image](https://user-images.githubusercontent.com/22287562/98055742-296fc900-1e79-11eb-9b31-ba788f1f6043.png)

Then I use nginx to reverse proxy http://vps-ip:3000 to https://vps-domain:443 and visit https://vps-domain:443 , no error occurred.

Finally I use https CDN to reverse proxy https://vps-domain:443 and visit https://cdn-domain:443, the error is same as the picture.

When I use `docker-composed up` to start containers and use https://cdn-domain:443 to visit umami, I can see error logs like that:

```
umami    | PrismaClientKnownRequestError2: Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Query.findManypageview.where.pageviewWhereInput.created_at.DateTimeNullableFilter.gte`: A value is required but not set., Query parsing/validation error at `Query.findManypageview.where.pageviewWhereInput.created_at`: Value types mismatch. Have: Object({"gte": Null}), want: DateTime, Query parsing/validation error at `Query.findManypageview.where.pageviewWhereInput.created_at`: Value types mismatch. Have: Object({"gte": Null}), want: Null]` at `Query.findManypageview.where.pageviewWhereInput.created_at`
umami    |     at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:78537:15)
umami    |     at runMicrotasks (<anonymous>)
umami    |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
umami    |   code: 'P2009',
umami    |   clientVersion: '2.10.1',
umami    |   meta: {
umami    |     query_validation_error: 'Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Query.findManypageview.where.pageviewWhereInput.created_at.DateTimeNullableFilter.gte`: A value is required but not set., Query parsing/validation error at `Query.findManypageview.where.pageviewWhereInput.created_at`: Value types mismatch. Have: Object({"gte": Null}), want: DateTime, Query parsing/validation error at `Query.findManypageview.where.pageviewWhereInput.created_at`: Value types mismatch. Have: Object({"gte": Null}), want: Null]',
umami    |     query_position: 'Query.findManypageview.where.pageviewWhereInput.created_at'
umami    |   }
umami    | }
...
(Error repeat)
```

When I visit https://cdn-domain:443 on dashboard page, use "F12 - Network" can see two errors:

<https://paste.ubuntu.com/p/zcdfrdnJ2B/>

<https://paste.ubuntu.com/p/Rj8WZbfRgr/>

But when I use http://vps-ip:3000 or https://vps-domain:443 to visit umami, website page or "F12 network page" or logs are well,  no error occurred.

Please pay attention to this issue if you have time, Thanks a lot~

**Comment by SuLingGG** [comment]
Finally I found the reason...

I use [又拍云(UPYUN)](http://upyun.com) as my CDN provider, there is a "Parameters Follow(参数跟随)" function in its control panel. 

By default the function is "Parameters do not follow (参数不跟随)" , it mains the parameters after the "?" in the user request URL will be ignored. So I can't get the correct information by CDN. 

When I set "Follow all the Parameters (参数跟随)", this problem is solved.

I'm sorry, it's my own reason...🥺🥺
