### ISSUE TITLE
Trouble installing on shared server

### ISSUE THREAD

**Issue by meirroth** [mikecao/umami#360]
This project looks amazing! I can't wait to try it out, and hopefully ditch Google Analytics for good!

I am trying to install umami on my shared hosting server, I followed the instructions here: https://umami.is/docs/install
Everything went smoothly until I ran the command `npm run build`, 
I would really appreciate if someone can help me with this.

Here is the ssh session copy:

(USER, SERVER and SUB-DIRECTORY are censored out for security)

```
[USER@SERVER ~]$ cd SUB-DIRECTORY
[USER@SERVER SUB-DIRECTORY]$ git clone https://github.com/mikecao/umami.git .
Cloning into '.'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 5137 (delta 8), reused 5 (delta 1), pack-reused 5107
Receiving objects: 100% (5137/5137), 1.68 MiB | 11.03 MiB/s, done.
Resolving deltas: 100% (3571/3571), done.
[USER@SERVER SUB-DIRECTORY]$ npm install
npm WARN deprecated @types/loud-rejection@2.0.0: This is a stub types definition. loud-rejection provides its own type definitions, so you do not need this installed.
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @types/schema-utils@2.4.0: This is a stub types definition. schema-utils provides its own type definitions, so you do not need this installed.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> @prisma/cli@2.10.1 preinstall /home/USER/SUB-DIRECTORY/node_modules/@prisma/cli
> node scripts/preinstall-entry.js

> bufferutil@4.0.2 install /home/USER/SUB-DIRECTORY/node_modules/bufferutil
> node-gyp-build

> utf-8-validate@5.0.3 install /home/USER/SUB-DIRECTORY/node_modules/utf-8-validate
> node-gyp-build

> sharp@0.26.2 install /home/USER/SUB-DIRECTORY/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/USER/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br

> @prisma/cli@2.10.1 install /home/USER/SUB-DIRECTORY/node_modules/@prisma/cli
> node scripts/install-entry.js

> bcrypt@5.0.0 install /home/USER/SUB-DIRECTORY/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[bcrypt] Success: "/home/USER/SUB-DIRECTORY/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote

> husky@4.3.0 install /home/USER/SUB-DIRECTORY/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> @prisma/engines@2.10.1-6-7d0087eadc7265e12d4b8d8c3516b02c4c965111 postinstall /home/USER/SUB-DIRECTORY/node_modules/@prisma/engines
> node download/index.js

> @ampproject/toolbox-optimizer@2.7.0-alpha.1 postinstall /home/USER/SUB-DIRECTORY/node_modules/@ampproject/toolbox-optimizer
> node lib/warmup.js

AMP OPTIMIZER Downloaded latest AMP runtime data.

> @prisma/client@2.10.1 postinstall /home/USER/SUB-DIRECTORY/node_modules/@prisma/client
> node scripts/postinstall.js

warning The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you have a Prisma schema file in a custom path, you will need to run
`prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
If you do not have a Prisma schema file yet, you can ignore this message.

> husky@4.3.0 postinstall /home/USER/SUB-DIRECTORY/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-intl@5.9.2 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @formatjs/ts-transformer@2.12.3 requires a peer of ts-jest@^26.4.0 but none is installed. You must install peer dependencies yourself.

added 1960 packages from 914 contributors and audited 1967 packages in 232.299s

158 packages are looking for funding
  run `npm fund` for details

found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[USER@SERVER SUB-DIRECTORY]$ node -v
v14.15.0
[USER@SERVER SUB-DIRECTORY]$ mysql -u USER_wa -p USER_umami < sql/schema.mysql.sql
Enter password:
[USER@SERVER SUB-DIRECTORY]$ npm run build

> umami@1.4.0 build /home/USER/SUB-DIRECTORY
> npm-run-all build-tracker build-lang build-geo build-db build-app

> umami@1.4.0 build-tracker /home/USER/SUB-DIRECTORY
> rollup -c rollup.tracker.config.js

tracker/index.js → public/umami.js...
[!] (plugin terser) Error: spawn ENOMEM
Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at spawn (child_process.js:553:9)
    at fork (child_process.js:121:10)
    at ChildProcessWorker.initialize (/home/USER/SUB-DIRECTORY/node_modules/rollup-plugin-terser/node_modules/jest-worker/build/workers/ChildProcessWorker.js:141:45)
    at new ChildProcessWorker (/home/USER/SUB-DIRECTORY/node_modules/rollup-plugin-terser/node_modules/jest-worker/build/workers/ChildProcessWorker.js:132:10)
    at WorkerPool.createWorker (/home/USER/SUB-DIRECTORY/node_modules/rollup-plugin-terser/node_modules/jest-worker/build/WorkerPool.js:44:12)
    at new BaseWorkerPool (/home/USER/SUB-DIRECTORY/node_modules/rollup-plugin-terser/node_modules/jest-worker/build/base/BaseWorkerPool.js:135:27)
    at new WorkerPool (/home/USER/SUB-DIRECTORY/node_modules/rollup-plugin-terser/node_modules/jest-worker/build/WorkerPool.js:30:1)
    at new JestWorker (/home/USER/SUB-DIRECTORY/node_modules/rollup-plugin-terser/node_modules/jest-worker/build/index.js:151:26)
    at Object.renderChunk (/home/USER/SUB-DIRECTORY/node_modules/rollup-plugin-terser/rollup-plugin-terser.js:22:23)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.4.0 build-tracker: `rollup -c rollup.tracker.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.4.0 build-tracker script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2020-11-05T22_26_14_188Z-debug.log
ERROR: "build-tracker" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.4.0 build: `npm-run-all build-tracker build-lang build-geo build-db build-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2020-11-05T22_26_14_303Z-debug.log
```

**Comment by mikecao** [comment]
`ENOMEM` means you ran out of memory. Maybe this solution will work, https://stackoverflow.com/questions/26193654/node-js-catch-enomem-error-thrown-after-spawn

**Comment by meirroth** [comment]
I am running this on a shared host server and it has 0 swap space,  I guess I will need to host it somewhere else, I will try Heroku.
Thanks

**Comment by mikecao** [comment]
You can also run on DigitalOcean for much cheaper, as little as $5 a month. https://umami.is/docs/running-on-digitalocean

**Comment by meirroth** [comment]
Hi @mikecao thank you for your help!
Do you know how much server resources is required to host this app?
Will this be enough? 2GB RAM • 8MB/s I/O • 7,500 IOPS • 20 Entry Processes • 450,000 iNodes

**Comment by meirroth** [comment]
I contacted my hosting support and this is what they found:

> While checking I couldn't see any resource limit reach issue for the subdomain. From the error log, it shows that issue is with the PHP version you are using for your domain name. See the below snippet for your clarification.
> ```
> 2020-11-05 17:19:43.989094 [NOTICE] [5319] [000.00.00.000:0000:HTTP2-15#APVH_SUB-DIRECTORY:443] [STDERR] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; AllImgs has a deprecated constructor in /usr/local/lib/php/autoindex/default.php on line 55
> 2020-11-05 17:19:43.989104 [NOTICE] [5319] [000.00.00.000:0000:HTTP2-15#APVH_SUB-DIRECTORY:443] [STDERR] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; FileStat has a deprecated constructor in /usr/local/lib/php/autoindex/default.php on line 116
> ```
> Please check with your developer which PHP version is supported for your app and you can able to change the PHP version accordingly using the PHP selector via cPanel.

What PHP version does umami need?

**Comment by mikecao** [comment]
It doesn't use php.

**Comment by barning** [comment]
I am sorry to reopen this topic, but many people are hosting on shared servers. I had luck with my hosting service uberspace, but now with the never umami versions even they kill the build process takes too much memory. Is there anything to reduce this?
I really love this project.
