### ISSUE TITLE
Can't reach database server at `db`:`5432` with docker-compose.yml

### ISSUE THREAD

**Issue by bronya5th** [mikecao/umami#403]
When I use the official [docker-compose.yml](https://github.com/mikecao/umami/blob/master/docker-compose.yml) to deploy the umami, I get the following error message：
~~~
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2020-12-04 20:01:07.608 UTC [1] LOG:  starting PostgreSQL 12.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
db_1     | 2020-12-04 20:01:07.609 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2020-12-04 20:01:07.609 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2020-12-04 20:01:07.612 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2020-12-04 20:01:07.633 UTC [21] LOG:  database system was interrupted; last known up at 2020-12-04 19:54:55 UTC
db_1     | 2020-12-04 20:01:07.711 UTC [21] LOG:  database system was not properly shut down; automatic recovery in progress
db_1     | 2020-12-04 20:01:07.715 UTC [21] LOG:  redo starts at 0/164DEA0
db_1     | 2020-12-04 20:01:07.716 UTC [21] LOG:  invalid record length at 0/164DF98: wanted 24, got 0
db_1     | 2020-12-04 20:01:07.717 UTC [21] LOG:  redo done at 0/164DF50
db_1     | 2020-12-04 20:01:07.727 UTC [1] LOG:  database system is ready to accept connections
umami_1  | PrismaClientInitializationError2: Can't reach database server at `db`:`5432`
umami_1  | 
umami_1  | Please make sure your database server is running at `db`:`5432`.
umami_1  |     at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:79361:15)
umami_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
umami_1  |   clientVersion: '2.12.1'
umami_1  | }
umami_1  | PrismaClientInitializationError2: Can't reach database server at `db`:`5432`
umami_1  | 
umami_1  | Please make sure your database server is running at `db`:`5432`.
umami_1  |     at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:79361:15)
umami_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
umami_1  |   clientVersion: '2.12.1'

~~~
I'm not good at writing docker-compose.yml , but I think something must be wrong. 

My OS Information: linux x86_64 Ubuntu 20.10LTS

**Comment by bronya5th** [comment]
Sorry, I forgot clone the repository so PostgreSQL can't read the [schema.postgresql.sql](https://github.com/mikecao/umami/blob/master/sql/schema.postgresql.sql) to create the sql.
