### ISSUE TITLE
Install Issue: Error: Missing or invalid database

### ISSUE THREAD

**Issue by MBadberg** [mikecao/umami#406]
Hi there,

i'm trying to install umami and it throws the Error: Missing or invalid database.

The database is there and accessible and user, password are correct.

npm run dev works.

Output from npm run Build:
```
markus@blogger:~/umami$ npm run build

> umami@1.9.0 build /home/markus/umami
> npm-run-all build-tracker build-lang build-geo build-db build-app


> umami@1.9.0 build-tracker /home/markus/umami
> rollup -c rollup.tracker.config.js


tracker/index.js → public/umami.js...
created public/umami.js in 516ms

> umami@1.9.0 build-lang /home/markus/umami
> npm-run-all format-lang compile-lang


> umami@1.9.0 format-lang /home/markus/umami
> node scripts/format-lang.js

/home/markus/umami/build/cs-CZ.json ✗
/home/markus/umami/build/da-DK.json ✗
/home/markus/umami/build/de-DE.json ✗
/home/markus/umami/build/el-GR.json ✗
/home/markus/umami/build/en-US.json ✗
/home/markus/umami/build/es-MX.json ✗
/home/markus/umami/build/fi-FI.json ✗
/home/markus/umami/build/fo-FO.json ✗
/home/markus/umami/build/fr-FR.json ✗
/home/markus/umami/build/he-IL.json ✗
/home/markus/umami/build/hi-IN.json ✗
/home/markus/umami/build/id-ID.json ✗
/home/markus/umami/build/ja-JP.json ✗
/home/markus/umami/build/mn-MN.json ✗
/home/markus/umami/build/nb-NO.json ✗
/home/markus/umami/build/nl-NL.json ✗
/home/markus/umami/build/pl-PL.json ✗
/home/markus/umami/build/pt-PT.json ✗
/home/markus/umami/build/ro-RO.json ✗
/home/markus/umami/build/ru-RU.json ✗
/home/markus/umami/build/sv-SE.json ✗
/home/markus/umami/build/ta-IN.json ✗
/home/markus/umami/build/tr-TR.json ✗
/home/markus/umami/build/uk-UA.json ✗
/home/markus/umami/build/zh-CN.json ✗
/home/markus/umami/build/zh-TW.json ✗
/home/markus/umami/lang/cs-CZ.json -> /home/markus/umami/build/cs-CZ.json
/home/markus/umami/lang/da-DK.json -> /home/markus/umami/build/da-DK.json
/home/markus/umami/lang/de-DE.json -> /home/markus/umami/build/de-DE.json
/home/markus/umami/lang/el-GR.json -> /home/markus/umami/build/el-GR.json
/home/markus/umami/lang/en-US.json -> /home/markus/umami/build/en-US.json
/home/markus/umami/lang/es-MX.json -> /home/markus/umami/build/es-MX.json
/home/markus/umami/lang/fi-FI.json -> /home/markus/umami/build/fi-FI.json
/home/markus/umami/lang/fo-FO.json -> /home/markus/umami/build/fo-FO.json
/home/markus/umami/lang/fr-FR.json -> /home/markus/umami/build/fr-FR.json
/home/markus/umami/lang/he-IL.json -> /home/markus/umami/build/he-IL.json
/home/markus/umami/lang/hi-IN.json -> /home/markus/umami/build/hi-IN.json
/home/markus/umami/lang/id-ID.json -> /home/markus/umami/build/id-ID.json
/home/markus/umami/lang/ja-JP.json -> /home/markus/umami/build/ja-JP.json
/home/markus/umami/lang/mn-MN.json -> /home/markus/umami/build/mn-MN.json
/home/markus/umami/lang/nb-NO.json -> /home/markus/umami/build/nb-NO.json
/home/markus/umami/lang/nl-NL.json -> /home/markus/umami/build/nl-NL.json
/home/markus/umami/lang/pl-PL.json -> /home/markus/umami/build/pl-PL.json
/home/markus/umami/lang/pt-PT.json -> /home/markus/umami/build/pt-PT.json
/home/markus/umami/lang/ro-RO.json -> /home/markus/umami/build/ro-RO.json
/home/markus/umami/lang/ru-RU.json -> /home/markus/umami/build/ru-RU.json
/home/markus/umami/lang/sv-SE.json -> /home/markus/umami/build/sv-SE.json
/home/markus/umami/lang/ta-IN.json -> /home/markus/umami/build/ta-IN.json
/home/markus/umami/lang/tr-TR.json -> /home/markus/umami/build/tr-TR.json
/home/markus/umami/lang/uk-UA.json -> /home/markus/umami/build/uk-UA.json
/home/markus/umami/lang/zh-CN.json -> /home/markus/umami/build/zh-CN.json
/home/markus/umami/lang/zh-TW.json -> /home/markus/umami/build/zh-TW.json

> umami@1.9.0 compile-lang /home/markus/umami
> formatjs compile-folder --ast build lang-compiled


> umami@1.9.0 build-geo /home/markus/umami
> node scripts/build-geo.js

Saved geo database: /home/markus/umami/public/geo/GeoLite2-Country.mmdb

> umami@1.9.0 build-db /home/markus/umami
> npm-run-all copy-db-schema build-db-client


> umami@1.9.0 copy-db-schema /home/markus/umami
> node scripts/copy-db-schema.js

/home/markus/umami/scripts/copy-db-schema.js:20
  throw new Error('Missing or invalid database');
  ^

Error: Missing or invalid database
    at Object.<anonymous> (/home/markus/umami/scripts/copy-db-schema.js:20:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.9.0 copy-db-schema: `node scripts/copy-db-schema.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.9.0 copy-db-schema script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/markus/.npm/_logs/2020-12-08T09_29_40_396Z-debug.log
ERROR: "copy-db-schema" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.9.0 build-db: `npm-run-all copy-db-schema build-db-client`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.9.0 build-db script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/markus/.npm/_logs/2020-12-08T09_29_40_426Z-debug.log
ERROR: "build-db" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.9.0 build: `npm-run-all build-tracker build-lang build-geo build-db build-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.9.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/markus/.npm/_logs/2020-12-08T09_29_40_472Z-debug.log`
``` 

I can connect to the database over telnet and another programm uses the databaseserver for its own database, too.

My .env looks like this(pw and username scrambled:
```
DATABASE_URL=(mysql://user:verysecurepw@localhost:3306/umami)
HASH_SALT=(kasjbdf)
``` 

I've no clue, what it could be. I think the error is on my site, but i need help to figure that out.

kind regards,
Markus

**Comment by mikecao** [comment]
Does your `.env` variables have parens around them? It should just be a plain string.

**Comment by MBadberg** [comment]
> Does your `.env` variables have parens around them? It should just be a plain string.

No, it is just that, what i've posted here.
Does it matter if it is MariaDB or directly MySQL? I use MariaDB.

**Comment by mikecao** [comment]
Well what you posted has parens. Try removing them.

And MariaDB should work as long as it is MySQL compatible.

**Comment by MBadberg** [comment]
Ah, you mean the brackets? -> ()

Ah, parenthesis. Now i understand. *head->table*

Thanks a lot. As i said, the error was on my side :-D 
Now it works :)

**Comment by stellarkey** [comment]
Great HELP! Thank!
