### ISSUE TITLE
umami keeps dying because /tmp/prisma-*.sock could not be found

### ISSUE THREAD

**Issue by simbo** [mikecao/umami#409]
I keep getting this error from time to time, which forces me to restart umami to make the dashboard work again:

```
2020-12-10 14:38:23,082 DEBG 'umami' stderr output:
PrismaClientKnownRequestError2: connect ENOENT /tmp/prisma-395d4bbf364fd00bc58da2d3.sock
    at PrismaClientFetcher.request (/home/simbo/umami/node_modules/@prisma/client/runtime/index.js:79355:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getSession (/home/simbo/umami/.next/server/pages/api/auth/verify.js:198:19)
    at async /home/simbo/umami/.next/server/pages/api/auth/verify.js:258:15 {
  code: 'ENOENT',
  clientVersion: '2.12.1',
  meta: undefined
}

2020-12-10 14:38:30,493 DEBG 'umami' stderr output:
PrismaClientKnownRequestError2: connect ENOENT /tmp/prisma-395d4bbf364fd00bc58da2d3.sock
    at PrismaClientFetcher.request (/home/simbo/umami/node_modules/@prisma/client/runtime/index.js:79355:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports.fJFN.__webpack_exports__.default (/home/simbo/umami/.next/server/pages/api/websites.js:1064:22)
    at async apiResolver (/home/simbo/umami/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async Server.handleApiRequest (/home/simbo/umami/node_modules/next/dist/next-server/server/next-server.js:63:403)
    at async Object.fn (/home/simbo/umami/node_modules/next/dist/next-server/server/next-server.js:55:530)
    at async Router.execute (/home/simbo/umami/node_modules/next/dist/next-server/server/router.js:24:67)
    at async Server.run (/home/simbo/umami/node_modules/next/dist/next-server/server/next-server.js:65:1023)
    at async Server.handleRequest (/home/simbo/umami/node_modules/next/dist/next-server/server/next-server.js:33:450) {
  code: 'ENOENT',
  clientVersion: '2.12.1',
  meta: undefined
}
```

Not sure if if this is an issue with my server or with umami... 
I am using umami 1.9.0 at the moment.

**Comment by mikecao** [comment]
umami uses the prisma library for database connections. It looks like it generates a socket file in the /tmp folder. Are you clearing out your /tmp folder or some other process doing it? You can also try submitting an issue with prisma, https://github.com/prisma/prisma

**Comment by simbo** [comment]
I am hosting umami on a shared hosting service (uberspace) and yes, the `/tmp` folder seems to get cleared from time to time.

I started a discussion at the prisma project: https://github.com/prisma/prisma/discussions/4706

**Comment by simbo** [comment]
Created issue about this at prisma: https://github.com/prisma/prisma/issues/4744

**Comment by simbo** [comment]
I have created a fork of umami: https://github.com/simbo/umami
Which includes a temporary fix using the dev channel of prisma as suggested here: https://github.com/prisma/prisma/discussions/4706#discussioncomment-222019

**Comment by adrianthomas** [comment]
> I have created a fork of umami: https://github.com/simbo/umami
> Which includes a temporary fix using the dev channel of prisma as suggested here: [prisma/prisma#4706 (reply in thread)](https://github.com/prisma/prisma/discussions/4706#discussioncomment-222019)

Thanks, I'm also on Uberspace and switched to your fork for now 👍

**Comment by simbo** [comment]
https://github.com/simbo/umami now up to date with umami v1.11.0

**Comment by mikecao** [comment]
@simbo Has this been fixed by the Prisma team yet?

**Comment by simbo** [comment]
Hi, sorry for the late response.

According to [this](https://github.com/prisma/prisma/issues/4744#issuecomment-762277950) and [that](https://github.com/prisma/prisma/issues/4557#issuecomment-762278415) comment in prisma issues, it seems like prisma switched back to tcp by default.
So this should be fixed in the latest version of prisma.
