### ISSUE TITLE
what am i doing wrong? docker issue

### ISSUE THREAD

**Issue by pefman** [mikecao/umami#428]
I clone the repo: git clone https://github.com/mikecao/umami.git
i pull the image as specified: docker pull ghcr.io/mikecao/umami:mysql-latest
edit the ports
edit the salt
docker-compose up -d 
everything starts, but i get internal server error. sql seems to be dead.

db_1     | 2021-01-09 00:33:48.083 UTC [29] FATAL:  password authentication failed for user "umami"
db_1     | 2021-01-09 00:33:48.083 UTC [29] DETAIL:  Password does not match for user "umami".
db_1     |      Connection matched pg_hba.conf line 99: "host all all all md5"
umami_1  | PrismaClientInitializationError2: Authentication failed against database server at `db`, the provided database credentials for `umami` are not valid.
umami_1  |
umami_1  | Please make sure to provide valid database credentials for the database server at `db`.
umami_1  |     at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:79361:15)
umami_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
umami_1  |   clientVersion: '2.12.1'
umami_1  | }

**Comment by pefman** [comment]
removed the volumes and reinstalled it, working now.
