### ISSUE TITLE
Error 502 [POST] /api/auth/login

### ISSUE THREAD

**Issue by gndclouds** [mikecao/umami#451]
Hi, 

I'm hosting the site on vervel and the database on render.com and keep getting this login error. 

Any recommendations I'm new to postsql?

```
2021-01-30T03:42:35.141Z	77e7ab6d-2315-4fd7-bc80-9b7556c24682	ERROR	PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: The table `public.account` does not exist in the current database.
    at PrismaClientFetcher.request (/var/task/node_modules/@prisma/client/runtime/index.js:78130:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2021',
  clientVersion: '2.14.0',
  meta: { table: 'public.account' }
}
2021-01-30T03:42:35.141Z	77e7ab6d-2315-4fd7-bc80-9b7556c24682	ERROR	PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: The table `public.account` does not exist in the current database.
    at PrismaClientFetcher.request (/var/task/node_modules/@prisma/client/runtime/index.js:78130:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2021',
  clientVersion: '2.14.0',
  meta: { table: 'public.account' }
}
2021-01-30T03:42:35.142Z	77e7ab6d-2315-4fd7-bc80-9b7556c24682	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: The table `public.account` does not exist in the current database.","reason":{"errorType":"Error","errorMessage":"The table `public.account` does not exist in the current database.","code":"P2021","clientVersion":"2.14.0","meta":{"table":"public.account"},"stack":["Error: The table `public.account` does not exist in the current database.","    at PrismaClientFetcher.request (/var/task/node_modules/@prisma/client/runtime/index.js:78130:15)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: The table `public.account` does not exist in the current database.","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:326:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```

**Comment by mikecao** [comment]
1) Make sure your database url is correct and doesn't include any weird characters that like confused the connection string parser
2) Make sure you can connect to the database yourself and check that the tables exist

**Comment by gndclouds** [comment]
That looks like that may be the issue, there is no public table in the DB. Should I make one manually and see if that resolves it? (I'm new to PSQL, so I apologizes for the novice nature of the question)

**Comment by mikecao** [comment]
public is the default schema. If you put the tables elsewhere, you can add `?schema=<schema_name>` to the end of your connection string to put it to the correct place.

**Comment by gndclouds** [comment]
Got it! It looks like when installing the original tables I mess up the paths. But all is now working! Thank you.
