### ISSUE TITLE
Vercel server error - code 500

### ISSUE THREAD

**Issue by stamatim** [mikecao/umami#502]
I have deployed a DigitalOcean cloud droplet which I use to run the MySQL database for my umami app. I forked the umami project from GitHub and set it up on Vercel with my `DATABASE_URL` and `HASH_SALT` environment variables. When I try to login with the default umami credentials, I get this error at the login page:

`{"error": {"code": "500", "message": "A server error has occurred"}}`

When taking a look at the Vercel function log from the latest deployment, I see this output:

```
[POST] /api/auth/login
13:59:55:91
2021-02-22T19:59:56.528Z	f4e88d43-5e40-4e24-929a-6b9ccc243b8c	ERROR	PrismaClientInitializationError2 [PrismaClientInitializationError]: Error querying the database: Server error: `ERROR HY000 (1130): Host 'ec2-35-175-112-207.compute-1.amazonaws.com' is not allowed to connect to this MySQL server'    at PrismaClientFetcher.request (/var/task/node_modules/@prisma/client/runtime/index.js:78461:15)    at processTicksAndRejections (internal/process/task_queues.js:93:5)    at async module.exports.Nrn6.__webpack_exports__.default (/var/task/.next/serverless/pages/api/auth/login.js:256:19)    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)    at async /var/task/.next/serverless/pages/api/auth/login.js:151:387 {  clientVersion: '2.15.0'}2021-02-22T19:59:56.529Z	f4e88d43-5e40-4e24-929a-6b9ccc243b8c	ERROR	PrismaClientInitializationError2 [PrismaClientInitializationError]: Error querying the database: Server error: `ERROR HY000 (1130): Host 'ec2-35-175-112-207.compute-1.amazonaws.com' is not allowed to connect to this MySQL server'    at PrismaClientFetcher.request (/var/task/node_modules/@prisma/client/runtime/index.js:78461:15)    at processTicksAndRejections (internal/process/task_queues.js:93:5)    at async module.exports.Nrn6.__webpack_exports__.default (/var/task/.next/serverless/pages/api/auth/login.js:256:19)    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)    at async /var/task/.next/serverless/pages/api/auth/login.js:151:387 {  clientVersion: '2.15.0'}2021-02-22T19:59:56.529Z	f4e88d43-5e40-4e24-929a-6b9ccc243b8c	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Error querying the database: Server error: `ERROR HY000 (1130): Host 'ec2-35-175-112-207.compute-1.amazonaws.com' is not allowed to connect to this MySQL server'","reason":{"errorType":"Error","errorMessage":"Error querying the database: Server error: `ERROR HY000 (1130): Host 'ec2-35-175-112-207.compute-1.amazonaws.com' is not allowed to connect to this MySQL server'","clientVersion":"2.15.0","stack":["Error: Error querying the database: Server error: `ERROR HY000 (1130): Host 'ec2-35-175-112-207.compute-1.amazonaws.com' is not allowed to connect to this MySQL server'","    at PrismaClientFetcher.request (/var/task/node_modules/@prisma/client/runtime/index.js:78461:15)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async module.exports.Nrn6.__webpack_exports__.default (/var/task/.next/serverless/pages/api/auth/login.js:256:19)","    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)","    at async /var/task/.next/serverless/pages/api/auth/login.js:151:387"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Error querying the database: Server error: `ERROR HY000 (1130): Host 'ec2-35-175-112-207.compute-1.amazonaws.com' is not allowed to connect to this MySQL server'","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}Unknown application error occurred
```

**Comment by mikecao** [comment]
Make sure you can connect to your database using the same credentials from elsewhere. Maybe you forgot to open up a port or the account you're using is bound to localhost only.

**Comment by EvidenceAdrien** [comment]
Have you dropped the tables in your database ? Files are provided in the repo.
