### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by summerjohn1** [mikecao/umami#596]
Today I started experiencing errors while building the app.

This error for each project page:
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messas/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decodertml?invariant=321 for the full message or use the non-minified dev environmentor full errors and additional helpful warnings.
    at S (C:\users\home\desktop\umami\node_modules\react\cjs\react.production.n.js:18:327)
    at Object.exports.useContext (C:\users\home\desktop\umami\node_modules\rea\cjs\react.production.min.js:22:269)
    at useRouter (C:\users\home\desktop\umami\node_modules\next\dist\client\roer.js:11:69)
    at useForceSSL (C:\users\home\desktop\umami\.next\server\pages\_app.js:2436)
    at App (C:\users\home\desktop\umami\.next\server\pages\_app.js:310:3)
    at d (C:\Users\home\Desktop\umami\node_modules\react-dom\cjs\react-dom-serr.node.production.min.js:33:498)
    at bb (C:\Users\home\Desktop\umami\node_modules\react-dom\cjs\react-dom-seer.node.production.min.js:36:16)
    at a.b.render (C:\Users\home\Desktop\umami\node_modules\react-dom\cjs\reacdom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\home\Desktop\umami\node_modules\react-dom\cjs\react-m-server.node.production.min.js:41:83)
    at exports.renderToString (C:\Users\home\Desktop\umami\node_modules\react-m\cjs\react-dom-server.node.production.min.js:52:138)
```
Build error:

```
Build error occurred
Error: Export encountered errors on following paths:
        /
        /404
        /500
        /dashboard/[[...id]]
        /login
        /logout
        /realtime
        /settings
        /settings/accounts
        /settings/profile
        /share/[...id]
        /test
        /website/[...id]
    at C:\Users\home\Desktop\umami\node_modules\next\dist\export\index.js:31:16
    at async Span.traceAsyncFn (C:\Users\home\Desktop\umami\node_modules\next\st\telemetry\trace\trace.js:5:584)
    at async C:\Users\home\Desktop\umami\node_modules\next\dist\build\index.js3:49
    at async Span.traceAsyncFn (C:\Users\home\Desktop\umami\node_modules\next\st\telemetry\trace\trace.js:5:584)
    at async C:\Users\home\Desktop\umami\node_modules\next\dist\build\index.js5:1475
    at async Span.traceAsyncFn (C:\Users\home\Desktop\umami\node_modules\next\st\telemetry\trace\trace.js:5:584)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.16.0 build-app: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.16.0 build-app script.
npm ERR! This is probably not a problem with npm. There is likely additional lging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\home\AppData\Roaming\npm-cache\_logs\2021-04-05T18_09_3925Z-debug.log
ERROR: "build-app" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.16.0 build: `npm-run-all build-tracker build-lang build-geo bld-db build-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.16.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional lging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\home\AppData\Roaming\npm-cache\_logs\2021-04-05T18_09_3947Z-debug.log
```

And I looked up the React error saying:

`Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.`

Everything was working fine and I didn't touch anything. I tried cleaning npm cache, reinstalling the app multiple times and on different devices. I still get this error.

Could you please let me know if you're having the same issue and how to fix this?
Thanks.

**Comment by mikecao** [comment]
Did you update your packages?
