### ISSUE TITLE
permission issue on tables after initial docker deploy with external postgresql instance

### ISSUE THREAD

**Issue by whysthatso** [mikecao/umami#626]
docker log shows this before running the schema.sql against the db:

```
}
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: The table `public.account` does not exist in the current database.
    at cb (/app/node_modules/@prisma/client/runtime/index.js:34774:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2021',
  clientVersion: '2.19.0',
  meta: { table: 'public.account' }
}
```

then i run `postgres@host:~$ psql -dumami -f schema.postgresql.sql`
which gives me this:
```
psql:schema.postgresql.sql:1: NOTICE:  table "event" does not exist, skipping
DROP TABLE
psql:schema.postgresql.sql:2: NOTICE:  table "pageview" does not exist, skipping
DROP TABLE
psql:schema.postgresql.sql:3: NOTICE:  table "session" does not exist, skipping
DROP TABLE
psql:schema.postgresql.sql:4: NOTICE:  table "website" does not exist, skipping
DROP TABLE
psql:schema.postgresql.sql:5: NOTICE:  table "account" does not exist, skipping
DROP TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
INSERT 0 1
```
so that looks pretty successful

but then when i want to log in with the default credentials admin/umami, i get this:

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42501"), message: "permission denied for table account", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("aclchk.c"), line: Some(3485), routine: Some("aclcheck_error") }) }) })
    at cb (/app/node_modules/@prisma/client/runtime/index.js:34778:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.19.0'
}
```

i loaded the schema with the postgres default admin user, so maybe the actual user i'm using for the app might not have all privileges. could anybody point me in the right direction for troubleshooting this?

**Comment by whysthatso** [comment]
ok nevermind, i think those might have been stale connections. the error magically disappeared now.

**Comment by 4ortytwo** [comment]
Hi @whysthatso ! I've followed these instructions and am now facing a similar error. Do you have any idea on why that might be?  

![image](https://user-images.githubusercontent.com/44406493/114541014-7b9ded00-9c56-11eb-8c99-446eff4c605e.png)

**Comment by whysthatso** [comment]
@4ortytwo yes, and that might have been part of the problem, but i am not that well versed with postgresql so i can't be certain.

**Comment by 4ortytwo** [comment]
Thanks, I solved the issue https://github.com/code-fabrik/open-knowledge/issues/1, had to run command from umami repo to create db. Will post solution later.
