### ISSUE TITLE
Error creating a database connection. (Error parsing connection string: invalid port number)

### ISSUE THREAD

**Issue by mskian** [mikecao/umami#67]
I setup umami software on my ubuntu 20.04 server with Node.js LTS (12) and MYSQL 8 Version
it can't connect the database
got this below error

```js
info  - Loaded env from /var/www/umami/.env
ready - started server on http://localhost:4000
PrismaClientInitializationError: Error creating a database connection. (Error parsing connection string: invalid port number)
    at PrismaClientFetcher.request (/var/www/umami/node_modules/@prisma/client/runtime/index.js:1:226686)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

My ENV configuration

```sh
DATABASE_URL=mysql://user:mypass@localhost:3306/webstatus
HASH_SALT=somerandomthings
```

Similar to #19

**Comment by mikecao** [comment]
Might be something to do with your password, https://github.com/prisma/prisma/issues/2000

**Comment by mskian** [comment]
Done fixed after changing the password characters
