### ISSUE TITLE
ERROR: "copy-db-schema" exited with 1.

### ISSUE THREAD

**Issue by the-mcnaveen** [mikecao/umami#68]
Trying to host Umami in Netlify. Here is the complete log.

Followed the stuff in #18 

```
11:35:39 AM: Build ready to start
11:35:43 AM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
11:35:43 AM: build-image tag: v3.4.1
11:35:43 AM: buildbot version: fcbc7a79f7372e5995cf02954ef19fc48d20c871
11:35:43 AM: Building without cache
11:35:43 AM: Starting to prepare the repo for build
11:35:43 AM: No cached dependencies found. Cloning fresh repo
11:35:43 AM: git clone https://github.com/the-mcnaveen/umami
11:35:44 AM: Preparing Git Reference refs/heads/master
11:35:45 AM: Starting build script
11:35:45 AM: Installing dependencies
11:35:45 AM: Python version set to 2.7
11:35:47 AM: v12.18.0 is already installed.
11:35:47 AM: Now using node v12.18.0 (npm v6.14.4)
11:35:47 AM: Started restoring cached build plugins
11:35:47 AM: Finished restoring cached build plugins
11:35:47 AM: Attempting ruby version 2.7.1, read from environment
11:35:49 AM: Using ruby version 2.7.1
11:35:49 AM: Using PHP version 5.6
11:35:49 AM: 5.2 is already installed.
11:35:49 AM: Using Swift version 5.2
11:35:49 AM: Started restoring cached node modules
11:35:49 AM: Finished restoring cached node modules
11:35:49 AM: Started restoring cached yarn cache
11:35:49 AM: Finished restoring cached yarn cache
11:35:49 AM: Installing yarn at version 1.22.4
11:35:49 AM: Installing Yarn!
11:35:49 AM: > Downloading tarball...
11:35:49 AM: [1/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz --> /tmp/yarn.tar.gz.AKbwkY3pJX
11:35:49 AM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
11:35:49 AM:                                  Dload  Upload   Total   Spent    Left  Speed
11:35:50 AM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
11:35:50 AM: 100    80  100    80    0     0    234      0 --:--:-- --:--:-- --:--:--   234
11:35:50 AM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
11:35:50 AM: 100    93  100    93    0     0    127      0 --:--:-- --:--:-- --:--:--  1500
11:35:50 AM: 100   643  100   643    0     0    645      0 --:--:-- --:--:-- --:--:--   645
11:35:51 AM: 100 1215k  100 1215k    0     0   855k      0  0:00:01  0:00:01 --:--:--  855k
11:35:51 AM: [2/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz.asc --> /tmp/yarn.tar.gz.AKbwkY3pJX.asc
11:35:51 AM: 100    84  100    84    0     0    922      0 --:--:-- --:--:-- --:--:--   922
11:35:51 AM: 100    97  100    97    0     0    808      0 --:--:-- --:--:-- --:--:--   808
11:35:51 AM: 100   647  100   647    0     0   4247      0 --:--:-- --:--:-- --:--:--  4247
11:35:51 AM: 100  1028  100  1028    0     0   5367      0 --:--:-- --:--:-- --:--:--  5367
11:35:51 AM: > Verifying integrity...
11:35:51 AM: gpg: Signature made Mon 09 Mar 2020 03:52:13 PM UTC using RSA key ID 69475BAA
11:35:51 AM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
11:35:51 AM: gpg: WARNING: This key is not certified with a trusted signature!
11:35:51 AM: gpg:          There is no indication that the signature belongs to the owner.
11:35:51 AM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
11:35:51 AM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
11:35:51 AM: > GPG signature looks good
11:35:51 AM: > Extracting to ~/.yarn...
11:35:51 AM: > Adding to $PATH...
11:35:52 AM: > Successfully installed Yarn 1.22.4! Please open another terminal where the `yarn` command will now be available.
11:35:52 AM: Installing NPM modules using Yarn version 1.22.4
11:35:52 AM: yarn install v1.22.4
11:35:52 AM: [1/4] Resolving packages...
11:35:53 AM: [2/4] Fetching packages...
11:36:13 AM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
11:36:13 AM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
11:36:13 AM: info fsevents@2.1.3: The platform "linux" is incompatible with this module.
11:36:13 AM: info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
11:36:13 AM: [3/4] Linking dependencies...
11:36:13 AM: warning " > react-simple-maps@2.1.2" has unmet peer dependency "prop-types@^15.7.2".
11:36:25 AM: [4/4] Building fresh packages...
11:36:35 AM: Done in 42.50s.
11:36:35 AM: NPM modules installed using Yarn
11:36:35 AM: Started restoring cached go cache
11:36:35 AM: Finished restoring cached go cache
11:36:35 AM: go version go1.14.4 linux/amd64
11:36:35 AM: go version go1.14.4 linux/amd64
11:36:35 AM: Installing missing commands
11:36:35 AM: Verify run directory
11:36:36 AM: ​
11:36:36 AM: ┌─────────────────────────────┐
11:36:36 AM: │        Netlify Build        │
11:36:36 AM: └─────────────────────────────┘
11:36:36 AM: ​
11:36:36 AM: ❯ Version
11:36:36 AM:   @netlify/build 3.3.0
11:36:36 AM: ​
11:36:36 AM: ❯ Flags
11:36:36 AM:   deployId: 5f45fbb30061096440765286
11:36:36 AM:   mode: buildbot
11:36:36 AM: ​
11:36:36 AM: ❯ Current directory
11:36:36 AM:   /opt/build/repo
11:36:36 AM: ​
11:36:36 AM: ❯ Config file
11:36:36 AM:   No config file was defined: using default values.
11:36:36 AM: ​
11:36:36 AM: ❯ Context
11:36:36 AM:   production
11:36:36 AM: ​
11:36:36 AM: ┌───────────────────────────────────┐
11:36:36 AM: │ 1. Build command from Netlify app │
11:36:36 AM: └───────────────────────────────────┘
11:36:36 AM: ​
11:36:36 AM: $ yarn build build-postgresql-schema && yarn build-mysql-client && yarn build
11:36:37 AM: yarn run v1.22.4
11:36:37 AM: $ npm-run-all build-tracker copy-db-schema build-db-client build-app build-postgresql-schema
11:36:37 AM: $ rollup -c rollup.tracker.config.js
11:36:37 AM: 
11:36:37 AM: tracker/index.js → public/umami.js...
11:36:38 AM: created public/umami.js in 775ms
11:36:39 AM: $ node scripts/copy-db-schema.js
11:36:39 AM: Database schema detected: https
11:36:39 AM: internal/fs/utils.js:230
11:36:39 AM:     throw err;
11:36:39 AM:     ^
11:36:39 AM: Error: ENOENT: no such file or directory, copyfile '/opt/build/repo/prisma/schema.https.prisma' -> '/opt/build/repo/prisma/schema.prisma'
11:36:39 AM:     at Object.copyFileSync (fs.js:1876:3)
11:36:39 AM:     at Object.<anonymous> (/opt/build/repo/scripts/copy-db-schema.js:16:4)
11:36:39 AM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
11:36:39 AM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
11:36:39 AM:     at Module.load (internal/modules/cjs/loader.js:986:32)
11:36:39 AM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
11:36:39 AM:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
11:36:39 AM:     at internal/main/run_main_module.js:17:47 {
11:36:39 AM:   errno: -2,
11:36:39 AM:   syscall: 'copyfile',
11:36:39 AM:   code: 'ENOENT',
11:36:39 AM:   path: '/opt/build/repo/prisma/schema.https.prisma',
11:36:39 AM:   dest: '/opt/build/repo/prisma/schema.prisma'
11:36:39 AM: }
11:36:39 AM: error Command failed with exit code 1.
11:36:39 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
11:36:39 AM: ERROR: "copy-db-schema" exited with 1.
11:36:39 AM: error Command failed with exit code 1.
11:36:39 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
11:36:39 AM: ​
11:36:39 AM: ┌─────────────────────────────┐
11:36:39 AM: │   "build.command" failed    │
11:36:39 AM: └─────────────────────────────┘
11:36:39 AM: ​
11:36:39 AM:   Error message
11:36:39 AM:   Command failed with exit code 1: yarn build build-postgresql-schema && yarn build-mysql-client && yarn build
11:36:39 AM: ​
11:36:39 AM:   Error location
11:36:39 AM:   In Build command from Netlify app:
11:36:39 AM:   yarn build build-postgresql-schema && yarn build-mysql-client && yarn build
11:36:39 AM: ​
11:36:39 AM:   Resolved config
11:36:39 AM:   build:
11:36:39 AM:     command: yarn build build-postgresql-schema && yarn build-mysql-client && yarn build
11:36:39 AM:     commandOrigin: ui
11:36:39 AM:     environment:
11:36:39 AM:       - DATABASE_URL
11:36:39 AM:       - HASH_SALT
11:36:39 AM:     publish: /opt/build/repo/public
11:36:39 AM: Caching artifacts
11:36:39 AM: Started saving node modules
11:36:39 AM: Finished saving node modules
11:36:39 AM: Started saving build plugins
11:36:39 AM: Finished saving build plugins
11:36:39 AM: Started saving yarn cache
11:36:39 AM: Finished saving yarn cache
11:36:39 AM: Started saving pip cache
11:36:39 AM: Finished saving pip cache
11:36:39 AM: Started saving emacs cask dependencies
11:36:39 AM: Finished saving emacs cask dependencies
11:36:39 AM: Started saving maven dependencies
11:36:39 AM: Finished saving maven dependencies
11:36:39 AM: Started saving boot dependencies
11:36:39 AM: Finished saving boot dependencies
11:36:39 AM: Started saving go dependencies
11:36:39 AM: Finished saving go dependencies
11:36:42 AM: Error running command: Build script returned non-zero exit code: 1
11:36:42 AM: Failing build: Failed to build site
11:36:42 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
11:36:42 AM: Finished processing build request in 59.099259499s
```

**Comment by mikecao** [comment]
I see this line:
```
11:36:39 AM: Database schema detected: https
```
That indicates your `DATABASE_URL` is not correct. It should start with either `mysql` or `postgresql`.

**Comment by the-mcnaveen** [comment]
Hey @mikecao It woked mate.

Btw, What should I set on **Publish directory** Currently it's on **Page**

Is this correct? The site isn't opening. Says "Page Not Found"

**Comment by the-mcnaveen** [comment]
Hey, @mikecao Just updating you.

We tried everything, But nothing works on Netlify. Kindly update the Readme file with Installation instruction or Deploy in Netlify button.

**Comment by mikecao** [comment]
According to this, https://www.netlify.com/blog/2020/05/04/building-a-markdown-blog-with-next-9.4-and-netlify/ the publish directory is called `out`.

You can also try this https://github.com/netlify/next-on-netlify

**Comment by the-mcnaveen** [comment]
@mskian

**Comment by mikecao** [comment]
Looks like I'll need to integrate the `next-on-netlify` package.

**Comment by the-mcnaveen** [comment]
Waiting for it. Please do the needful, Thanks

**Comment by mikecao** [comment]
There is a bug blocking netlify deployment currently. I raised an issue here https://github.com/vercel/next.js/issues/16618. You can try using Vercel instead for now.

**Comment by the-mcnaveen** [comment]
Will wait until it gets fixed. ♥️

**Comment by andreweick** [comment]
does https://github.com/netlify/next-on-netlify announcement from 3 days ago simplify this?

**Comment by mikecao** [comment]
Closing this. Will track this issue on #203
