### ISSUE TITLE
Build error occurred: require() of ES modules is not supported

### ISSUE THREAD

**Issue by benja135** [mikecao/umami#693]
Hello,

I followed the tutorial to install Umami and I have the following error when I try to build (npm run build):
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Benjamin\Documents\Développement\umami\node_modules\d3-array\src\index.js
require() of ES modules is not supported.
require() of C:\Users\Benjamin\Documents\Développement\umami\node_modules\d3-array\src\index.js from C:\Users\Benjamin\Documents\Développement\umami\node_modules\d3-geo\dist\d3-geo.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\Benjamin\Documents\Développement\umami\node_modules\d3-array\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\Users\Benjamin\Documents\Développement\umami\node_modules\d3-geo\dist\d3-geo.js:3:81
    at Object.<anonymous> (C:\Users\Benjamin\Documents\Développement\umami\node_modules\d3-geo\dist\d3-geo.js:6:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  type: 'NodeError',
  code: 'ERR_REQUIRE_ESM'
}
```
I have the same problem on two different environments.
Node v14.17.0
Npm 7.16.0

**Comment by mikecao** [comment]
Can you try using a different version of node?

**Comment by redpik** [comment]
Same error.
Node v12.20.0
Npm 7.16.0

**Comment by renatkalimulin** [comment]
Same error while trying to update to v 1.18:

node - v14.17.0
npm - 6.14.13

```
> Build error occurred
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/umami-1.18.0/node_modules/d3-array/src/index.js
require() of ES modules is not supported.
require() of /home/umami-1.18.0/node_modules/d3-array/src/index.js from /home/umami-1.18.0/node_modules/react-simple-maps/node_modules/d3-geo/dist/d3-geo.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/umami-1.18.0/node_modules/d3-array/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/umami-1.18.0/node_modules/react-simple-maps/node_modules/d3-geo/dist/d3-geo.js:3:81
    at Object.<anonymous> (/home/umami-1.18.0/node_modules/react-simple-maps/node_modules/d3-geo/dist/d3-geo.js:6:2)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32) {
  type: 'NodeError',
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by wowi42** [comment]
Same here

**Comment by whalehub** [comment]
I'm getting the same error using Node v14.17.0 and NPM v7.16.0 on Debian 10.

```
> umami@1.18.0 build-app
> next build

info  - Loaded env from /opt/umami/.env
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully

> Build error occurred
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /opt/umami/node_modules/d3-array/src/index.js
require() of ES modules is not supported.
require() of /opt/umami/node_modules/d3-array/src/index.js from /opt/umami/node_modules/d3-geo/dist/d3-geo.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /opt/umami/node_modules/d3-array/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /opt/umami/node_modules/d3-geo/dist/d3-geo.js:3:81
    at Object.<anonymous> (/opt/umami/node_modules/d3-geo/dist/d3-geo.js:6:2)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32) {
  type: 'NodeError',
  code: 'ERR_REQUIRE_ESM'
}
info  - Collecting page data .ERROR: "build-app" exited with 1.
```

**Comment by walela** [comment]
> this is due to the new [d3-array update](https://github.com/d3/d3-array/pull/202)
> 
> so to resolve the build error, downgrade `d3-array`:
> 
> * add `"d3-array": "^2.12.1"` to `"devDependencies"` in `packages.json`
> * then run `npm install`

worked for me, thanks!

**Comment by benja135** [comment]
Indeed, it works! Thank you!

**Comment by wowi42** [comment]
PR Done https://github.com/mikecao/umami/pull/701

**Comment by mIcHyAmRaNe** [comment]
personally i'm not fan of that PR, 
i just share the fix here rather than opening a PR because, i think that's a temporary fix

we need to fix that while having newer version of dependencies
and if needed, we open an issue in the concerned dependency to discuss about a bug with it's developers to find a solution.

**Comment by mikecao** [comment]
I would like to know why this error is occurring. I get that `d3-array` changed their package to `type: "module"`, but I'd like to know the root cause. Maybe it's an issue with the Next.js build command. I don't think continuing to add problematic packages will solve it in the long run since there may be other packages in the future that declare `type: "module"` as well.

**Comment by mikecao** [comment]
Looks like this is an issue with Next.js, https://github.com/vercel/next.js/issues/23725

**Comment by wowi42** [comment]
@mIcHyAmRaNe @mikecao what could be a good solution is to not use ^ or ~ and stick to strict versions. If everybody was doing this small effort (including in 3rd parties like next), this would not happen...

**Comment by mikecao** [comment]
Looks like this is fixed from the upgrade to Next.js 12.
