### ISSUE TITLE
MaxMind databases from 'geolite2-redist' package installation failed.

### ISSUE THREAD

**Issue by lastingman** [mikecao/umami#73]
node: v12.18.3
macOS: Catalina 10.15.6

```bash
❯ yarn  
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-simple-maps@2.1.2" has unmet peer dependency "prop-types@^15.7.2".
[4/4] 🔨  Building fresh packages...
[1/7] ⠄ @prisma/cli
[2/7] ⠄ bcrypt
[3/7] ⠄ geolite2-redist
[4/7] ⠄ @ampproject/toolbox-optimizer
error /Users/like/repo/fork/umami/node_modules/geolite2-redist: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/like/repo/fork/umami/node_modules/geolite2-redist
Output:
Downloading MaxMind databases from mirror...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
```

**Comment by hugomd** [comment]
@lastingman This looks like a network failure, if you try again it may work. If the host is down, you may just have to wait unfortunately, unless there's a mirror to point it to..

**Comment by lastingman** [comment]
> @lastingman This looks like a network failure, if you try again it may work. If the host is down, you may just have to wait unfortunately, unless there's a mirror to point it to..

Hi @hugomd,

I tried several times, it doesn't work.

I narrow down the problem, it happens at file `./node_modules/geolite2-redist/scripts/download-helper.js:21`

![image](https://user-images.githubusercontent.com/10057502/91570173-926a2a80-e978-11ea-8aa3-cf073e299d07.png)

The `https` request is not working properly.

**Comment by mikecao** [comment]
Since this is due to another module, you'll have to raise an issue with the `geolite2-redist` repo.

**Comment by xyhcode** [comment]
$ node scripts/build-geo.js
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 443
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-geo" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1

I also had a similar issue and tried several times without getting a solution
