### ISSUE TITLE
getting "Internal Server Error" inconsistency 

### ISSUE THREAD

**Issue by YogliB** [mikecao/umami#778]
I'm using Umami v1.22.0, hosted on Vercel (cloned to Github) and the DB is on Supabase (Postgres).

Sometimes the stats don't work, sometimes it's the page views, but there's always some server issue.

I'm not sure where to start with this, are there some logs I'm missing?

**Comment by mikecao** [comment]
In Vercel, click on `View Function Logs`, which will display any errors it runs into.

**Comment by YogliB** [comment]
here's the details:

```
[GET] /api/website/1/pageviews?start_at=1630789200000&end_at=1631393999999&unit=day&tz=Asia%2FJerusalem
23:10:44:61
Function Status:
500
Edge Status:
500
Duration:
232.75 ms
Init Duration:
N/A
Memory Used:
152 MB
ID:
z2lg9-1631304644612-deebd26d0833
User Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
2021-09-10T20:10:44.908Z	e0c81667-275c-4272-9480-d6c95a9ac895	ERROR	PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]: Raw query failed. Code: `42P05`. Message: `db error: ERROR: prepared statement "s9" already exists`
    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:36374:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async module.exports.cmhW.__webpack_exports__.default (/var/task/.next/server/pages/api/website/[id]/pageviews.js:1140:35)
    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:66:462)
    at async Object.fn (/var/task/node_modules/next/dist/next-server/server/next-server.js:58:580)
    at async Router.execute (/var/task/node_modules/next/dist/next-server/server/router.js:25:67)
    at async Server.run (/var/task/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async Server.handleRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:32:504) {
  code: 'P2010',
  clientVersion: '2.29.1',
  meta: {
    code: '42P05',
    message: 'db error: ERROR: prepared statement "s9" already exists'
  }
}
```

**Comment by YogliB** [comment]
Found a clue:
https://dev.to/prisma/set-up-a-free-postgresql-database-on-supabase-to-use-with-prisma-3pk6

**Comment by YogliB** [comment]
Solved it, it's a thing with Prisma & Supabase.
How can I add it to the docs for future reference?

**Comment by mikecao** [comment]
@YogliB the repo for the website is here, https://github.com/mikecao/umami.is. Feel free to add some content

**Comment by sumul** [comment]
I just ran into this same issue. In case anyone else ends up here: 

**Solution: you must add `?pgbouncer=true` to your DATABASE_URL environment variable.** 

It should end up looking like this:

`postgres://postgres:[YOUR-PASSWORD]@[host].supabase.co:6543/postgres?pgbouncer=true`

See https://github.com/prisma/prisma/issues/11643 for more details.
