### ISSUE TITLE
Can't resolve './files/noto-sans-jp-japanese-400-normal.woff2' in '/srv/apps/umami/node_modules/@fontsource/noto-sans-jp'

### ISSUE THREAD

**Issue by kulame** [mikecao/umami#795]
i try to build this project by npm run build

but it occur some error.

> Build error occurred
Error: > Build failed because of webpack errors
    at /srv/apps/umami/node_modules/next/dist/build/index.js:17:924
    at async Span.traceAsyncFn (/srv/apps/umami/node_modules/next/dist/telemetry/trace/trace.js:6:584)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.0.0 build-app: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.0.0 build-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kula/.npm/_logs/2021-09-23T11_01_31_858Z-debug.log
ERROR: "build-app" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.0.0 build: `npm-run-all build-tracker build-lang build-geo build-db build-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by imlonghao** [comment]
Same problem here, can be reproduce by a Dockerfile

```
FROM node:12.18-alpine
ENV DATABASE_URL "mysql://username:mypassword@localhost:3306/mydb" \
    DATABASE_TYPE=mysql
ARG UMAMI_VERSION=1.22.0
WORKDIR /app/umami-${UMAMI_VERSION}
ADD https://github.com/mikecao/umami/archive/refs/tags/v${UMAMI_VERSION}.tar.gz /app
RUN tar xf /app/v${UMAMI_VERSION}.tar.gz -C /app && rm /app/v${UMAMI_VERSION}.tar.gz && npm install && npm run build
```

My error log

```
> umami@1.22.0 build-app /app/umami-1.22.0
> next build

info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Checking validity of types...
info  - Creating an optimized production build...
Failed to compile.

./node_modules/@fontsource/noto-sans-jp/japanese-400.css
Error: Can't resolve './files/noto-sans-jp-japanese-400-normal.woff2' in '/app/umami-1.22.0/node_modules/@fontsource/noto-sans-jp'
    at runMicrotasks (<anonymous>)


> Build error occurred
Error: > Build failed because of webpack errors
    at /app/umami-1.22.0/node_modules/next/dist/build/index.js:17:924
    at async Span.traceAsyncFn (/app/umami-1.22.0/node_modules/next/dist/telemetry/trace/trace.js:6:584)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.22.0 build-app: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.22.0 build-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-24T02_38_30_867Z-debug.log
ERROR: "build-app" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umami@1.22.0 build: `npm-run-all build-tracker build-lang build-geo build-db build-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umami@1.22.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-24T02_38_30_947Z-debug.log
```

**Comment by adonisd** [comment]
The ref has a way to solve it, just edit the package.json so that it explicitly chooses 4.5.0 instead of ^4.5.0,
If you want add this to your Dockerfile and it should work:

    RUN sed -i 's#"@fontsource/inter": "^4.5.0"#"@fontsource/inter": "4.5.0"#g' package.json
    RUN sed -i 's#"@fontsource/noto-sans-jp": "^4.5.0"#"@fontsource/noto-sans-jp": "4.5.0"#g' package.json
    RUN sed -i 's#"@fontsource/noto-sans-sc": "^4.5.0"#"@fontsource/noto-sans-sc": "4.5.0"#g' package.json
    RUN sed -i 's#"@fontsource/noto-sans-tc": "^4.5.0"#"@fontsource/noto-sans-tc": "4.5.0"#g' package.json
