### ISSUE TITLE
An unexpected error occured

### ISSUE THREAD

**Issue by nevoodoo** [mikecao/umami#83]
The frontend crashes with an "An unexpected error occured"

Looking at Vercel error logs, the following is outputted:

```
[GET] /api/website/1/metrics?start_at=1598277600000&end_at=1598882399999
18:00:45:87
2020-08-31T08:00:46.032Z	44392247-ca36-472e-9022-08237f4c6666	ERROR	TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at RKDr.__webpack_exports__.default (/var/task/.next/serverless/pages/api/website/[id]/metrics.js:695:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async module.exports.fI55.__webpack_exports__.default (/var/task/.next/serverless/pages/api/website/[id]/metrics.js:860:11)
2020-08-31T08:00:46.032Z	44392247-ca36-472e-9022-08237f4c6666	ERROR	TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at RKDr.__webpack_exports__.default (/var/task/.next/serverless/pages/api/website/[id]/metrics.js:695:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async module.exports.fI55.__webpack_exports__.default (/var/task/.next/serverless/pages/api/website/[id]/metrics.js:860:11)
2020-08-31T08:00:46.033Z	44392247-ca36-472e-9022-08237f4c6666	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot convert undefined or null to object","reason":{"errorType":"TypeError","errorMessage":"Cannot convert undefined or null to object","stack":["TypeError: Cannot convert undefined or null to object","    at Function.keys (<anonymous>)","    at RKDr.__webpack_exports__.default (/var/task/.next/serverless/pages/api/website/[id]/metrics.js:695:24)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)","    at async module.exports.fI55.__webpack_exports__.default (/var/task/.next/serverless/pages/api/website/[id]/metrics.js:860:11)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot convert undefined or null to object","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```

**Comment by RizkyRajitha** [comment]
i had the same issue 

what is your db url

if it is something like this
`DATABASE_URL=postgres://postgres:123@localhost:5432/postgres`
 changed that to
`DATABASE_URL=postgresql://postgres:123@localhost:5432/postgres`

start with `postgresql`

**Comment by nevoodoo** [comment]
I fixed that issue so it’s not the DATABASE_URL. I’m able to login to the dashboard and change my password etc just fine.

**Comment by mikecao** [comment]
@nevoodoo Which version are you using?

**Comment by nevoodoo** [comment]
@mikecao I changed the files to make the DATABASE_URL work with “postgres” which btw is hosted on Heroku and is version 12.4. I can verify the tabled were created correctly and the connection works through Postico. I hope that was what you were after? ;)

**Comment by mikecao** [comment]
I meant which version of umami. There have been lots of bug fixes since the first release.

**Comment by nevoodoo** [comment]
@mikecao i just cloned from this repo last night so must be the latest version I guess

**Comment by mikecao** [comment]
Can you try adding `DATABASE_TYPE=postgresql` to your `.env` file?

**Comment by nevoodoo** [comment]
Here is a deployment log from Vercel:

```
15:01:13.457  	Cloning gitlab.com/xtecy/my-umami-server (Branch: master, Commit: 3e16fb5)
15:01:14.377  	Cloning completed in 920ms
15:01:14.379  	Analyzing source code...
15:01:14.983  	Installing build runtime...
15:01:15.453  	Build runtime installed: 468.955ms
15:01:15.926  	Looking up build cache...
15:01:16.069  	Build cache found. Downloading...
15:01:19.001  	Build cache downloaded [107.13 MB]: 2931.321ms
15:01:19.488  	Installing dependencies...
15:01:19.720  	yarn install v1.22.4
15:01:19.818  	[1/4] Resolving packages...
15:01:20.273  	success Already up-to-date.
15:01:20.282  	Done in 0.57s.
15:01:20.504  	Running "npm run build-postgresql-client && npm run build"
15:01:20.724  	> umami@0.19.0 build-postgresql-client /vercel/495f97a
15:01:20.724  	> dotenv prisma generate -- --schema=./prisma/schema.postgres.prisma
15:01:21.765  	✔ Generated Prisma Client to ./node_modules/@prisma/client in 65ms
15:01:21.765  	You can now start using Prisma Client in your code:
15:01:21.765  	```
15:01:21.765  	import { PrismaClient } from '@prisma/client'
15:01:21.765  	// or const { PrismaClient } = require('@prisma/client')
15:01:21.765  	const prisma = new PrismaClient()
15:01:21.765  	```
15:01:21.765  	Explore the full API: http://pris.ly/d/client
15:01:22.073  	> umami@0.19.0 build /vercel/495f97a
15:01:22.073  	> npm-run-all build-tracker copy-db-schema build-db-client build-app
15:01:22.419  	> umami@0.19.0 build-tracker /vercel/495f97a
15:01:22.419  	> rollup -c rollup.tracker.config.js
15:01:22.600  	tracker/index.js → public/umami.js...
15:01:23.047  	created public/umami.js in 447ms
15:01:23.328  	> umami@0.19.0 copy-db-schema /vercel/495f97a
15:01:23.328  	> node scripts/copy-db-schema.js
15:01:23.381  	Database schema detected: postgres
15:01:23.381  	Copied /vercel/495f97a/prisma/schema.postgres.prisma to /vercel/495f97a/prisma/schema.prisma
15:01:23.603  	> umami@0.19.0 build-db-client /vercel/495f97a
15:01:23.603  	> dotenv prisma generate
15:01:24.635  	✔ Generated Prisma Client to ./node_modules/@prisma/client in 65ms
15:01:24.635  	You can now start using Prisma Client in your code:
15:01:24.635  	```
15:01:24.635  	import { PrismaClient } from '@prisma/client'
15:01:24.635  	// or const { PrismaClient } = require('@prisma/client')
15:01:24.635  	const prisma = new PrismaClient()
15:01:24.635  	```
15:01:24.635  	Explore the full API: http://pris.ly/d/client
15:01:24.911  	> umami@0.19.0 build-app /vercel/495f97a
15:01:24.911  	> next build
15:01:25.560  	info  - Creating an optimized production build...
15:01:45.900  	info  - Compiled successfully
15:01:45.900  	info  - Collecting page data...
15:01:46.529  	info  - Generating static pages (0/10)
15:01:46.765  	info  - Generating static pages (1/10)
15:01:46.794  	info  - Generating static pages (2/10)
15:01:46.804  	info  - Generating static pages (3/10)
15:01:46.844  	info  - Generating static pages (4/10)
15:01:46.866  	info  - Generating static pages (5/10)
15:01:46.871  	info  - Generating static pages (6/10)
15:01:46.915  	info  - Generating static pages (7/10)
15:01:47.037  	info  - Generating static pages (8/10)
15:01:47.080  	info  - Generating static pages (9/10)
15:01:47.119  	info  - Generating static pages (10/10)
15:01:47.119  	info  - Finalizing page optimization...
15:01:47.132  	Page                                                           Size     First Load JS
15:01:47.132  	┌ ○ /                                                          270 B          69.7 kB
15:01:47.132  	├   /_app                                                      0 B            69.5 kB
15:01:47.132  	├ ○ /404                                                       311 B          83.3 kB
15:01:47.132  	├ ○ /account                                                   300 B           108 kB
15:01:47.132  	├   └ css/4c92a58df6575f89abbf.css                             1.61 kB
15:01:47.133  	├ λ /api/account                                               0 B            69.5 kB
15:01:47.133  	├ λ /api/account/[id]                                          0 B            69.5 kB
15:01:47.133  	├ λ /api/account/password                                      0 B            69.5 kB
15:01:47.133  	├ λ /api/accounts                                              0 B            69.5 kB
15:01:47.133  	├ λ /api/auth/login                                            0 B            69.5 kB
15:01:47.133  	├ λ /api/auth/logout                                           0 B            69.5 kB
15:01:47.133  	├ λ /api/auth/verify                                           0 B            69.5 kB
15:01:47.133  	├ λ /api/collect                                               0 B            69.5 kB
15:01:47.133  	├ λ /api/share/[id]                                            0 B            69.5 kB
15:01:47.133  	├ λ /api/website                                               0 B            69.5 kB
15:01:47.133  	├ λ /api/website/[id]                                          0 B            69.5 kB
15:01:47.133  	├ λ /api/website/[id]/active                                   0 B            69.5 kB
15:01:47.133  	├ λ /api/website/[id]/events                                   0 B            69.5 kB
15:01:47.133  	├ λ /api/website/[id]/metrics                                  0 B            69.5 kB
15:01:47.133  	├ λ /api/website/[id]/pageviews                                0 B            69.5 kB
15:01:47.133  	├ λ /api/website/[id]/rankings                                 0 B            69.5 kB
15:01:47.133  	├ λ /api/websites                                              0 B            69.5 kB
15:01:47.133  	├ ○ /dashboard                                                 1.3 kB          270 kB
15:01:47.133  	├   └ css/eef59640bfd38ce6f934.css                             1.9 kB
15:01:47.133  	├ ○ /login                                                     969 B           105 kB
15:01:47.133  	├   └ css/593046c5d3a62dbeb6cc.css                             1.33 kB
15:01:47.133  	├ ○ /logout                                                    317 B          69.8 kB
15:01:47.133  	├ ○ /settings                                                  7.46 kB         115 kB
15:01:47.133  	├   └ css/67fcbdde57f58799ff7a.css                             1.94 kB
15:01:47.133  	├ ○ /share/[...id]                                             719 B           320 kB
15:01:47.133  	├ ○ /test                                                      689 B          83.7 kB
15:01:47.133  	└ ○ /website/[...id]                                           811 B           321 kB
15:01:47.133  	+ First Load JS shared by all                                  69.5 kB
15:01:47.133  	  ├ chunks/0328004b18dbca9d70f9be5bfa3108943c47d56c.de3642.js  5.99 kB
15:01:47.133  	  ├ chunks/500b5a1d2b643a4c391e5b5b5d3aac2b96523de3.078c38.js  4.82 kB
15:01:47.133  	  ├ chunks/ed2584126e27a96ef798621a2b6886b4a721d4b7.1027d5.js  10 kB
15:01:47.133  	  ├ chunks/framework.4cba9b.js                                 40.4 kB
15:01:47.133  	  ├ chunks/main.301883.js                                      6.69 kB
15:01:47.133  	  ├ chunks/pages/_app.d74e9c.js                                747 B
15:01:47.133  	  ├ chunks/webpack.ccf5ab.js                                   751 B
15:01:47.133  	  └ css/f356f8c49403e9ecbfce.css                               6.54 kB
15:01:47.134  	λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
15:01:47.134  	○  (Static)  automatically rendered as static HTML (uses no initial props)
15:01:47.134  	●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
15:01:47.134  	   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
15:01:47.134  	Redirects
15:01:47.134  	┌ source: /:path+/
15:01:47.134  	├ destination: /:path+
15:01:47.134  	└ permanent: true
15:01:47.134  	 
15:01:50.971  	Traced Next.js serverless functions for external files in: 3727.535ms
15:02:09.014  	Compressed shared serverless function files: 18043.241ms
15:02:09.169  	All serverless functions created in: 153.839ms
15:02:09.481  	Uploading build outputs...
15:02:16.918  	Build completed. Populating build cache...
15:02:35.513  	Uploading build cache [107.15 MB]...
15:02:37.217  	Build cache uploaded: 1703.647ms
15:02:37.232  	Done with "package.json"
```

**Comment by mikecao** [comment]
There is database detection in the code itself. You can't simply rename things. The `DATABASE_TYPE` variable is there specifically so you can tell umami what database you're using. Also you only need to run one step, `npm run build`

**Comment by nevoodoo** [comment]
@mikecao I see. I was following some other tutorial while troubleshooting so maybe that's where I got derailed. Please excuse my stupidity. All fixed now. I cloned the repo afresh and did as you told. Works like a charm x
