### ISSUE TITLE
[PrismaClientKnownRequestError]: connect ECONNREFUSED

### ISSUE THREAD

**Issue by vlfz** [mikecao/umami#876]
After build and start `umami`, i'm trying to login to admin account, but internal server error with this in logs:
```
PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]: connect ECONNREFUSED ::1:46367
    at cb (/root/umami/node_modules/@prisma/client/runtime/index.js:36374:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async __WEBPACK_DEFAULT_EXPORT__ (/root/umami/.next/server/pages/api/auth/login.js:115:21)
    at async Object.apiResolver (/root/umami/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/root/umami/node_modules/next/dist/server/next-server.js:1017:9)
    at async Object.fn (/root/umami/node_modules/next/dist/server/next-server.js:904:37)
    at async Router.execute (/root/umami/node_modules/next/dist/server/router.js:210:32)
    at async Server.run (/root/umami/node_modules/next/dist/server/next-server.js:1088:29)
    at async Server.handleRequest (/root/umami/node_modules/next/dist/server/next-server.js:304:20) {
  code: 'ECONNREFUSED',
  clientVersion: '2.29.1',
  meta: undefined
}
```

**Comment by mikecao** [comment]
`connect ECONNREFUSED` means your database is not allowing connections.

**Comment by vlfz** [comment]
> `connect ECONNREFUSED` means your database is not allowing connections.

But he's allowing connections lol

**Comment by cywio** [comment]
also had this issue, it turned out to be a [Node 17 incompatibility with prisma](https://github.com/prisma/prisma/issues/10018#issuecomment-954755144), if you have 17 maybe try the latest LTS?

**Comment by vlfz** [comment]
> also had this issue, it turned out to be a [Node 17 incompatibility with prisma](https://github.com/prisma/prisma/issues/10018#issuecomment-954755144), if you have 17 maybe try the latest LTS?

oh ok, thanks
