### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by atmonshi** [mikecao/umami#921]
after updating to v1.25.0
I cant accsess the `/dashboard` or any site stats page `/website/1/blog` or `/settings/profile`
getting the error:

`Application error: a client-side exception has occurred (see the browser console for more information).`

the console output:

```
framework-91d7f78b5b4003c8.js:1 SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at m (_app-55a9810cbf8ca279.js:1:409752)
    at f (752-fdafd5228e3660dc.js:1:16156)
    at Nn (803-a5a0aa08ee49a343.js:1:38783)
    at ro (framework-91d7f78b5b4003c8.js:1:59430)
    at Hu (framework-91d7f78b5b4003c8.js:1:111888)
    at Pi (framework-91d7f78b5b4003c8.js:1:99062)
    at xi (framework-91d7f78b5b4003c8.js:1:98990)
    at _i (framework-91d7f78b5b4003c8.js:1:98853)
    at vi (framework-91d7f78b5b4003c8.js:1:95819)
uu @ framework-91d7f78b5b4003c8.js:1
a.componentDidCatch.n.callback @ framework-91d7f78b5b4003c8.js:1
fa @ framework-91d7f78b5b4003c8.js:1
hu @ framework-91d7f78b5b4003c8.js:1
Li @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Ti @ framework-91d7f78b5b4003c8.js:1
vi @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Ql @ framework-91d7f78b5b4003c8.js:1
Hl @ framework-91d7f78b5b4003c8.js:1
fi @ framework-91d7f78b5b4003c8.js:1
No @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
s @ main-6dbd9d9da1881058.js:1
(anonymous) @ main-6dbd9d9da1881058.js:1
S.forEach.e.<computed> @ main-6dbd9d9da1881058.js:1
u @ 803-a5a0aa08ee49a343.js:1
l @ 803-a5a0aa08ee49a343.js:1
Promise.then (async)
u @ 803-a5a0aa08ee49a343.js:1
l @ 803-a5a0aa08ee49a343.js:1
Promise.then (async)
u @ 803-a5a0aa08ee49a343.js:1
l @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
h @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
Fi @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Oi @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ framework-91d7f78b5b4003c8.js:1
I @ framework-91d7f78b5b4003c8.js:1
w.port1.onmessage @ framework-91d7f78b5b4003c8.js:1
main-6dbd9d9da1881058.js:1 SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at m (_app-55a9810cbf8ca279.js:1:409752)
    at f (752-fdafd5228e3660dc.js:1:16156)
    at Nn (803-a5a0aa08ee49a343.js:1:38783)
    at ro (framework-91d7f78b5b4003c8.js:1:59430)
    at Hu (framework-91d7f78b5b4003c8.js:1:111888)
    at Pi (framework-91d7f78b5b4003c8.js:1:99062)
    at xi (framework-91d7f78b5b4003c8.js:1:98990)
    at _i (framework-91d7f78b5b4003c8.js:1:98853)
    at vi (framework-91d7f78b5b4003c8.js:1:95819)
ye @ main-6dbd9d9da1881058.js:1
fn @ main-6dbd9d9da1881058.js:1
value @ main-6dbd9d9da1881058.js:1
a.componentDidCatch.n.callback @ framework-91d7f78b5b4003c8.js:1
fa @ framework-91d7f78b5b4003c8.js:1
hu @ framework-91d7f78b5b4003c8.js:1
Li @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Ti @ framework-91d7f78b5b4003c8.js:1
vi @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Ql @ framework-91d7f78b5b4003c8.js:1
Hl @ framework-91d7f78b5b4003c8.js:1
fi @ framework-91d7f78b5b4003c8.js:1
No @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
s @ main-6dbd9d9da1881058.js:1
(anonymous) @ main-6dbd9d9da1881058.js:1
S.forEach.e.<computed> @ main-6dbd9d9da1881058.js:1
u @ 803-a5a0aa08ee49a343.js:1
l @ 803-a5a0aa08ee49a343.js:1
Promise.then (async)
u @ 803-a5a0aa08ee49a343.js:1
l @ 803-a5a0aa08ee49a343.js:1
Promise.then (async)
u @ 803-a5a0aa08ee49a343.js:1
l @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
h @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
Fi @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Oi @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ framework-91d7f78b5b4003c8.js:1
I @ framework-91d7f78b5b4003c8.js:1
w.port1.onmessage @ framework-91d7f78b5b4003c8.js:1
main-6dbd9d9da1881058.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ye @ main-6dbd9d9da1881058.js:1
fn @ main-6dbd9d9da1881058.js:1
value @ main-6dbd9d9da1881058.js:1
a.componentDidCatch.n.callback @ framework-91d7f78b5b4003c8.js:1
fa @ framework-91d7f78b5b4003c8.js:1
hu @ framework-91d7f78b5b4003c8.js:1
Li @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Ti @ framework-91d7f78b5b4003c8.js:1
vi @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Ql @ framework-91d7f78b5b4003c8.js:1
Hl @ framework-91d7f78b5b4003c8.js:1
fi @ framework-91d7f78b5b4003c8.js:1
No @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
s @ main-6dbd9d9da1881058.js:1
(anonymous) @ main-6dbd9d9da1881058.js:1
S.forEach.e.<computed> @ main-6dbd9d9da1881058.js:1
u @ 803-a5a0aa08ee49a343.js:1
l @ 803-a5a0aa08ee49a343.js:1
Promise.then (async)
u @ 803-a5a0aa08ee49a343.js:1
l @ 803-a5a0aa08ee49a343.js:1
Promise.then (async)
u @ 803-a5a0aa08ee49a343.js:1
l @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
h @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
(anonymous) @ 803-a5a0aa08ee49a343.js:1
Fi @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Oi @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ framework-91d7f78b5b4003c8.js:1
I @ framework-91d7f78b5b4003c8.js:1
w.port1.onmessage @ framework-91d7f78b5b4003c8.js:1
```

**Comment by atmonshi** [comment]
git pull
yarn install
yarn run build
yarn start << by daemon

**Comment by mikecao** [comment]
Looks like an issue with next.js. Trying deleting your `node_modules` folder and installing again.

**Comment by atmonshi** [comment]
Are there DB changes? like the `Owner` column?
it seems only chart pages are affected.

**Comment by mikecao** [comment]
No DB changes. Can you send the actual error that is being sent from `next-dev.js?3515:32 The above error occurred in the <WebsiteChart> component:`?

**Comment by atmonshi** [comment]
sure:

```
The above error occurred in the <WebsiteChart> component:

    at WebsiteChart (webpack-internal:///./components/metrics/WebsiteChart.js:147:28)
    at div
    at div
    at div
    at Page (webpack-internal:///./components/layout/Page.js:108:9)
    at WebsiteDetails (webpack-internal:///./components/pages/WebsiteDetails.js:103:27)
    at main
    at Layout (webpack-internal:///./components/layout/Layout.js:23:23)
    at DetailsPage (webpack-internal:///./pages/website/[...id].js:55:84)
    at IntlProvider (webpack-internal:///./node_modules/react-intl/lib/src/components/provider.js:88:47)
    at Intl (webpack-internal:///./pages/_app.js:75:28)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at App (webpack-internal:///./pages/_app.js:112:27)
    at StyleRegistry (webpack-internal:///./node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:90:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:331:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:770:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:891:27)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
window.console.error @ next-dev.js?3515:32
logCapturedError @ react-dom.development.js?ac89:20085
callback @ react-dom.development.js?ac89:20154
callCallback @ react-dom.development.js?ac89:12318
commitUpdateQueue @ react-dom.development.js?ac89:12339
commitLifeCycles @ react-dom.development.js?ac89:20709
commitLayoutEffects @ react-dom.development.js?ac89:23426
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
commitRootImpl @ react-dom.development.js?ac89:23151
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
commitRoot @ react-dom.development.js?ac89:22990
performSyncWorkOnRoot @ react-dom.development.js?ac89:22329
eval @ react-dom.development.js?ac89:11327
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?ac89:11322
flushSyncCallbackQueue @ react-dom.development.js?ac89:11309
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21893
dispatchAction @ react-dom.development.js?ac89:16139
_callee$ @ useFetch.js?5683:29
tryCatch @ runtime.js?2d8a:45
invoke @ runtime.js?2d8a:274
prototype.<computed> @ runtime.js?2d8a:97
asyncGeneratorStep @ useFetch.js?5683:5
_next @ useFetch.js?5683:5
Promise.then (async)
asyncGeneratorStep @ useFetch.js?5683:5
_next @ useFetch.js?5683:5
eval @ useFetch.js?5683:5
eval @ useFetch.js?5683:5
_loadData @ useFetch.js?5683:16
loadData @ useFetch.js?5683:16
eval @ useFetch.js?5683:43
setTimeout (async)
eval @ useFetch.js?5683:43
invokePassiveEffectCreate @ react-dom.development.js?ac89:23487
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
flushPassiveEffectsImpl @ react-dom.development.js?ac89:23574
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushPassiveEffects @ react-dom.development.js?ac89:23447
eval @ react-dom.development.js?ac89:23324
workLoop @ scheduler.development.js?bcd2:417
flushWork @ scheduler.development.js?bcd2:390
performWorkUntilDeadline @ scheduler.development.js?bcd2:157
next-dev.js?3515:32 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at WebsiteDetails (webpack-internal:///./components/pages/WebsiteDetails.js:103:27)
    at main
    at Layout (webpack-internal:///./components/layout/Layout.js:23:23)
    at DetailsPage (webpack-internal:///./pages/website/[...id].js:55:84)
    at IntlProvider (webpack-internal:///./node_modules/react-intl/lib/src/components/provider.js:88:47)
    at Intl (webpack-internal:///./pages/_app.js:75:28)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at App (webpack-internal:///./pages/_app.js:112:27)
    at StyleRegistry (webpack-internal:///./node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
```


another one in `/profile` page for `DateRangeSetting`


```
next-dev.js?3515:32 The above error occurred in the <DateRangeSetting> component:

    at DateRangeSetting (webpack-internal:///./components/settings/DateRangeSetting.js:66:77)
    at dd
    at dl
    at ProfileSettings (webpack-internal:///./components/settings/ProfileSettings.js:53:72)
    at div
    at div
    at MenuLayout (webpack-internal:///./components/layout/MenuLayout.js:25:22)
    at div
    at Page (webpack-internal:///./components/layout/Page.js:108:9)
    at Settings (webpack-internal:///./components/pages/Settings.js:35:72)
    at main
    at Layout (webpack-internal:///./components/layout/Layout.js:23:23)
    at SettingsPage (webpack-internal:///./pages/settings/index.js:21:84)
    at IntlProvider (webpack-internal:///./node_modules/react-intl/lib/src/components/provider.js:88:47)
    at Intl (webpack-internal:///./pages/_app.js:75:28)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at App (webpack-internal:///./pages/_app.js:112:27)
    at StyleRegistry (webpack-internal:///./node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:90:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:331:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:770:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:891:27)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
window.console.error @ next-dev.js?3515:32
logCapturedError @ react-dom.development.js?ac89:20085
callback @ react-dom.development.js?ac89:20154
callCallback @ react-dom.development.js?ac89:12318
commitUpdateQueue @ react-dom.development.js?ac89:12339
commitLifeCycles @ react-dom.development.js?ac89:20709
commitLayoutEffects @ react-dom.development.js?ac89:23426
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
commitRootImpl @ react-dom.development.js?ac89:23151
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
commitRoot @ react-dom.development.js?ac89:22990
performSyncWorkOnRoot @ react-dom.development.js?ac89:22329
eval @ react-dom.development.js?ac89:11327
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?ac89:11322
flushSyncCallbackQueue @ react-dom.development.js?ac89:11309
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21893
updateContainer @ react-dom.development.js?ac89:25482
legacyRenderSubtreeIntoContainer @ react-dom.development.js?ac89:26037
render @ react-dom.development.js?ac89:26103
renderReactElement @ index.js?46cb:491
doRender @ index.js?46cb:710
_callee$ @ index.js?46cb:384
tryCatch @ runtime.js?2d8a:45
invoke @ runtime.js?2d8a:274
prototype.<computed> @ runtime.js?2d8a:97
asyncGeneratorStep @ index.js?46cb:31
_next @ index.js?46cb:49
eval @ index.js?46cb:54
eval @ index.js?46cb:46
render @ index.js?46cb:406
subscription @ index.js?46cb:343
notify @ router.js?8684:1255
set @ router.js?8684:955
_callee$ @ router.js?8684:787
tryCatch @ runtime.js?2d8a:45
invoke @ runtime.js?2d8a:274
prototype.<computed> @ runtime.js?2d8a:97
asyncGeneratorStep @ router.js?8684:1
_next @ router.js?8684:1
Promise.then (async)
asyncGeneratorStep @ router.js?8684:1
_next @ router.js?8684:1
Promise.then (async)
asyncGeneratorStep @ router.js?8684:1
_next @ router.js?8684:1
Promise.then (async)
asyncGeneratorStep @ router.js?8684:1
_next @ router.js?8684:1
eval @ router.js?8684:1
eval @ router.js?8684:1
change @ router.js?8684:808
push @ router.js?8684:507
instance.<computed> @ router.js?31fc:150
handleSelect @ MenuLayout.js?481e:22
onClick @ NavMenu.js?122a:25
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?ac89:4070
executeDispatch @ react-dom.development.js?ac89:8243
processDispatchQueueItemsInOrder @ react-dom.development.js?ac89:8275
processDispatchQueue @ react-dom.development.js?ac89:8288
dispatchEventsForPlugins @ react-dom.development.js?ac89:8299
eval @ react-dom.development.js?ac89:8508
batchedEventUpdates$1 @ react-dom.development.js?ac89:22396
batchedEventUpdates @ react-dom.development.js?ac89:3745
dispatchEventForPluginEventSystem @ react-dom.development.js?ac89:8507
attemptToDispatchEvent @ react-dom.development.js?ac89:6005
dispatchEvent @ react-dom.development.js?ac89:5924
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
discreteUpdates$1 @ react-dom.development.js?ac89:22413
discreteUpdates @ react-dom.development.js?ac89:3756
dispatchDiscreteEvent @ react-dom.development.js?ac89:5889
```

**Comment by mikecao** [comment]
Can you trying deleting all your localStorage values?

**Comment by atmonshi** [comment]
I just logged in from my phone and it’s working 
so I guess it’s from the local storage 

I’ll confirm when I get back home

**Comment by cywio** [comment]
Just to add onto this, i got the same client side error trying to set a default date range in the settings, local storage had it set to undefined no matter which value i selected

**Comment by ShubhamVerma1811** [comment]
Facing the same issue,
When the All Time value is set from the Settings page, then it crashed because the value is set as undefined

**Comment by atmonshi** [comment]
yes, confirmed, clearing the local storage fixed it for me

![Screen Shot 2022-01-19 at 4 22 00 PM](https://user-images.githubusercontent.com/1952412/150139272-997d3935-0df4-4e7b-bf9a-39e7c8820a0b.png)
.

**Comment by t3brightside** [comment]
> Just to add onto this, i got the same client side error trying to set a default date range in the settings, local storage had it set to undefined no matter which value i selected

Same for me, reproduced it in different browsers.

**Comment by sozonome** [comment]
Still happen using `dev` branch

![image](https://user-images.githubusercontent.com/17046154/153543320-7d377386-4278-4cae-b8d9-d13822da10e2.png)

**Comment by mikecao** [comment]
Fixed in v1.26.0.

**Comment by t3brightside** [comment]
Still having the same problem with v1.26.

**Comment by t3brightside** [comment]
Certainly so...
Changing 'Default date range' in Profile settings results in 'umami.date-range:undefined'

**Comment by winterrific** [comment]
Same here. Was able to reproduce this. Whenever I change the "default date range" the local storage entry comes back. (v1.26)
