### ISSUE TITLE
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.

### ISSUE THREAD

**Issue by riccardodivirgilio** [mikecao/umami#931]
My docker deployed instance is logging the following error on production:

$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)

I'm not sure how to get additional information of why this is happening.

**Comment by mikecao** [comment]
Looks like there is a problem with creating the session (when someone visits the page, we generate and save the session). But that should only happen when we register a pageview. Does the rest of the app run fine?

**Comment by riccardodivirgilio** [comment]
yes the rest of the app runs fine, however I think a lot of visits are not logged because of this.
this is the result of logging after running the app for 10 days (the app is reporting around 200 views/day):

```
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at getSession (/app/.next/server/chunks/1649.js:218:13)
```
