### ISSUE TITLE
Install with docker-compose

### ISSUE THREAD

**Issue by Innei** [mikecao/umami#960]
Hi, I am using docker-compose to self-host this service. But login failed. got error 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/41265413/154023583-5b2958ed-26a9-4d36-85a0-2a325669c176.png">

There is docker log.

```
umami-db-1     |
umami-db-1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
umami-db-1     |
umami-db-1     | 2022-02-15 08:29:50.822 UTC [1] LOG:  starting PostgreSQL 12.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
umami-db-1     | 2022-02-15 08:29:50.823 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
umami-db-1     | 2022-02-15 08:29:50.824 UTC [1] LOG:  listening on IPv6 address "::", port 5432
umami-db-1     | 2022-02-15 08:29:50.828 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
umami-db-1     | 2022-02-15 08:29:50.848 UTC [21] LOG:  database system was shut down at 2022-02-15 08:29:22 UTC
umami-db-1     | 2022-02-15 08:29:50.853 UTC [1] LOG:  database system is ready to accept connections
umami-umami-1  | yarn run v1.22.17
umami-umami-1  | $ next start
umami-umami-1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
umami-db-1     | 2022-02-15 08:30:03.600 UTC [28] ERROR:  relation "public.account" does not exist at character 201
umami-db-1     | 2022-02-15 08:30:03.600 UTC [28] STATEMENT:  SELECT "public"."account"."user_id", "public"."account"."username", "public"."account"."password", "public"."account"."is_admin", "public"."account"."created_at", "public"."account"."updated_at" FROM "public"."account" WHERE "public"."account"."username" = $1 LIMIT $2 OFFSET $3
umami-umami-1  | PrismaClientKnownRequestError: The table `public.account` does not exist in the current database.
umami-umami-1  |     at cb (/app/node_modules/@prisma/client/runtime/index.js:38683:17) {
umami-umami-1  |   code: 'P2021',
umami-umami-1  |   clientVersion: '3.6.0',
umami-umami-1  |   meta: { table: 'public.account' }
umami-umami-1  | }
```

It looks database scheme not created at first start.

**Comment by Innei** [comment]
manully exec 

```
docker exec -i <<docker_container_id>> psql -U umami -d umami < schema.postgresql.sql
```

It worked.

But it there a way to exec it automatically?

**Comment by Innei** [comment]
## Install with Docker compose script

```sh
mkdir umami
cd umami
wget https://cdn.jsdelivr.net/gh/mikecao/umami@master/sql/schema.postgresql.sql
wget https://cdn.jsdelivr.net/gh/mikecao/umami@master/docker-compose.yml
docker-compose up -d
docker exec -i umami-db-1 psql -U umami -d umami < schema.postgresql.sql
```

**Comment by boly38** [comment]
hi, would be great to add this details to 
readme section #installing-with-docker

**Comment by deshetti** [comment]
@Innei Running using `docker-compose` worked just fine for me.

This line in the `docker-compose.yml` should create the required schema when the Postgres starts for the first time: https://github.com/mikecao/umami/blob/1e4c3ebf3b7a280f4a61cc40f2e6cc34933bf47e/docker-compose.yml#L22

Looking at the following line in your logs, seems like the database initialization was skipped for somereason:

```
umami-db-1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
```

One reason I could think of is if you were using an existing instance of Postgres that you started previously on Docker.

IMO, the `docker-compose.yml` file is doing what is supposed to do.

**Comment by presswizards** [comment]
I just updated a working docker-compose instance, and am now getting the same error. I'm using the same old DB, it seems the new version added a new table? How to update the DB to work with the new version?

Error in output is pretty clear:

The table `public.account` does not exist in the current database.

**Comment by presswizards** [comment]
I was able to change the docker-compose file to point to a new data directory, and it successfully initialized the database and is working again, I just lost all my data, which I don't care about as it was just a test site. 

However, I would like info on how to perform future updates that have tables added, and how this could have been solved differently I guess, so that the old data is retained, or there's an update process that adjusts tables as needed.

**Comment by mikecao** [comment]
There have been no tables changes ever in umami. Possibly something else is going on with your docker instance.

**Comment by presswizards** [comment]
Oh wow ok, well a working instance and database suddenly gives a table does not exist error when the code is updated, hence the concern. Perhaps the database had an issue or corruption after the update then, but @Innei had the same error, so not sure. But the new instance with new DB is working fine now, so all good.

**Comment by Fandermill** [comment]
Hi,

I am having trouble getting started as well when I use the docker-compose file. I get the same 'internal server error' message as the original poster.

I then did a `docker-compose down` and removed the volume through the docker CLI. So my next try should be a fresh configuration, right?

After doing a `docker-compose up -d` again and getting the same error, I catched the docker-compose logs:
```
Attaching to umami_umami_1, umami_db_1
db_1     | The files belonging to this database system will be owned by user "postgres".
db_1     | This user must also own the server process.
db_1     |
db_1     | The database cluster will be initialized with locale "en_US.utf8".
db_1     | The default database encoding has accordingly been set to "UTF8".
db_1     | The default text search configuration will be set to "english".
db_1     |
db_1     | Data page checksums are disabled.
db_1     |
db_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1     | creating subdirectories ... ok
db_1     | selecting dynamic shared memory implementation ... posix
db_1     | selecting default max_connections ... 100
db_1     | selecting default shared_buffers ... 128MB
db_1     | selecting default time zone ... UTC
db_1     | creating configuration files ... ok
db_1     | running bootstrap script ... ok
db_1     | sh: locale: not found
db_1     | 2022-04-12 21:03:44.135 UTC [31] WARNING:  no usable system locales were found
db_1     | performing post-bootstrap initialization ... ok
db_1     | syncing data to disk ... ok
db_1     |
db_1     |
db_1     | Success. You can now start the database server using:
db_1     |
db_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1     |
db_1     | initdb: warning: enabling "trust" authentication for local connections
db_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_1     | --auth-local and --auth-host, the next time you run initdb.
db_1     | waiting for server to start....2022-04-12 21:03:45.103 UTC [37] LOG:  starting PostgreSQL 12.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db_1     | 2022-04-12 21:03:45.104 UTC [37] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2022-04-12 21:03:45.127 UTC [38] LOG:  database system was shut down at 2022-04-12 21:03:44 UTC
db_1     | 2022-04-12 21:03:45.132 UTC [37] LOG:  database system is ready to accept connections
db_1     |  done
db_1     | server started
db_1     | CREATE DATABASE
db_1     |
db_1     |
db_1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/schema.postgresql.sql
db_1     | psql:/docker-entrypoint-initdb.d/schema.postgresql.sql: error: could not read from input file: Is a directory
db_1     |
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     |
db_1     | 2022-04-12 21:03:46.776 UTC [1] LOG:  starting PostgreSQL 12.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db_1     | 2022-04-12 21:03:46.777 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2022-04-12 21:03:46.778 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2022-04-12 21:03:46.780 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2022-04-12 21:03:46.816 UTC [21] LOG:  database system was interrupted; last known up at 2022-04-12 21:03:45 UTC
db_1     | 2022-04-12 21:03:46.865 UTC [21] LOG:  database system was not properly shut down; automatic recovery in progress
db_1     | 2022-04-12 21:03:46.867 UTC [21] LOG:  redo starts at 0/164E388
db_1     | 2022-04-12 21:03:46.867 UTC [21] LOG:  invalid record length at 0/164E480: wanted 24, got 0
db_1     | 2022-04-12 21:03:46.867 UTC [21] LOG:  redo done at 0/164E438
db_1     | 2022-04-12 21:03:46.878 UTC [1] LOG:  database system is ready to accept connections
db_1     | 2022-04-12 21:03:55.567 UTC [28] ERROR:  relation "public.account" does not exist at character 201
db_1     | 2022-04-12 21:03:55.567 UTC [28] STATEMENT:  SELECT "public"."account"."user_id", "public"."account"."username", "public"."account"."password", "public"."account"."is_admin", "public"."account"."created_at", "public"."account"."updated_at" FROM "public"."account" WHERE "public"."account"."username" = $1 LIMIT $2 OFFSET $3
umami_1  | yarn run v1.22.17
umami_1  | $ next start
umami_1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
umami_1  | warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
umami_1  | PrismaClientKnownRequestError: The table `public.account` does not exist in the current database.
umami_1  |     at Object.request (/app/node_modules/@prisma/client/runtime/index.js:45578:15) {
umami_1  |   code: 'P2021',
umami_1  |   clientVersion: '3.12.0',
umami_1  |   meta: { table: 'public.account' }
umami_1  | }
```

So, I also do see 

```
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
```

But right before that, I see 

```
db_1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/schema.postgresql.sql
db_1     | psql:/docker-entrypoint-initdb.d/schema.postgresql.sql: error: could not read from input file: Is a directory
```

I hope this is helpfull.
